### ISSUE TITLE
add option for text position

### ISSUE THREAD

**Issue by dinosauros** [AdiAddons/AdiButtonAuras#208]
It would be great if text position option could be implemented.
Thanks

**Comment by Rainrider** [comment]
Sorry for the late reply. I will take a look, but time won't permit it until at the least the release of Legion.

**Comment by mixMugz** [comment]
+1 for enhancement.

Also as addition possible make cooldown like omniCC? (Background shadowed clockwise)

**Comment by Rainrider** [comment]
Sorry, I know this is a shallow response but time constraints are pretty tight for me right now. GUI improvements are the last on my list for the foreseeable future.

**Comment by Rainrider** [comment]
Could you guys please give the latest alpha a go and provide some feedback? @mspykerez

It is maybe a bit limited but please see if it helps you. `x Offset` is the distance between the text and the left/right button border. A positive value makes the text shrink, negative makes it grow. Positive `y Offset` moves the text up, negative - down. `Position` is relative to the button and is either top or bottom. The settings are shared among all buttons.

**Comment by mspykerez** [comment]
Theres a 3rd position that is not listed to move, that is the stack count when you get the bottom text active AND you have a stack count at the same time, like solar and lunar empowerment... Just tested again it seems this particular stack count is a blizzard default stack count which the addon cannot move :(

**Comment by Rainrider** [comment]
Yes, if the default count is shown and the custom one is the same as the default, we don't show ours. And we don't touch anything on the underlying action buttons. If you have an option to move this in Bartender (you mentioned you use it in your other issue), then please use that.

**Comment by Rainrider** [comment]
Implemented with 2eb20ae38cd34c5741cbf06f961c3031980a0936
