### ISSUE TITLE
Legion Support

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/AdiButtonAuras#209]
As all of the classes were revamped for the next expansion, I removed all the WoD spell data. Also updates are needed for some of the libraries that ABA relies upon.

Libraries status:
- [x] [LibArtifactData-1.0](https://github.com/Rainrider/LibArtifactData-1.0)
- [x] [LibDispellable-1.0](https://github.com/AdiAddons/LibDispellable-1.0/tree/legion)
- [x] [LibItemBuffs-1.0](https://github.com/AdiAddons/LibItemBuffs-1.0)
- [ ] [LibPlayerSpells-1.0](https://github.com/AdiAddons/LibPlayerSpells-1.0/tree/legion) (https://github.com/AdiAddons/LibPlayerSpells-1.0/milestone/1)
- [x] [LibSpellbook-1.0](https://github.com/AdiAddons/LibSpellbook-1.0/tree/legion)

**Comment by nickdekruijk** [comment]
Dunno if this is the right place to mention it but I miss a warning for shamans Totem Mastery talent http://www.wowhead.com/spell=210643/totem-mastery
It gives multiple buffs/aura's but I think tracking just one of them is fine. If none present i want my Totem Mastery button to glow.

**Comment by Rainrider** [comment]
There are 4 buffs associated with Totem Mastery. All 4 don't have a duration so the default behavior is to show the green border as long as at least one of those buffs is present on the player. You can use the "show missing" dropdown if you want to be notified when the buffs are not on you. For that type /aba in chat to open the options, click on the plus sign, click on "Spells & Items", click on the green overlay that appears on top of the Totem Mastery button and select the show missing method you want. If you select "hint", it will only display in combat.

The next time please open a new issue for your problem unless there is an open one with your problem.

**Comment by nickdekruijk** [comment]
Oh, you must have added it in the alpha release of today? it's working now, wasn't yesterday

**Comment by Rainrider** [comment]
19 hours ago actually. Please always try the latest version before posting issues.
