### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by SinisterBrain** [AdiAddons/AdiButtonAuras#211]
Upon login I received this error.  I'm _fairly_ certain I got the latest ( Version: 2.0-beta )off Wowace.
I have disabled all my addons only loading ABA with the same error (Well, I used bugsack/buggrabber to grab the error)
Interestingly enough, functionality seems unimpeded.  

My apologies if this is a known issue.  I didn't read through all the issues listed.

4x AdiButtonAuras\rules\Common.lua:202: Unknown symbol 'LibPlayerSpells'.
[C]: ?
AdiButtonAuras\core\SafeEnv.lua:87: in function <AdiButtonAuras\core\SafeEnv.lua:84>
AdiButtonAuras\rules\Common.lua:202: in function <AdiButtonAuras\rules\Common.lua:22>
[C]: ?
AdiButtonAuras\core\Core.lua:373: in function <AdiButtonAuras\core\Core.lua:365>
AdiButtonAuras\core\Core.lua:388: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals:
nil

**Comment by Grimsbain** [comment]
This is fixed in "common: add back missing LPS" it just needs to pushed out.

**Comment by SinisterBrain** [comment]
Ah ok.  Sorry about that.  
Thank you!

**Comment by Rainrider** [comment]
I pushed an alpha version to curse/wowace. I actually pushed the fix yesterday but the wowace packager didn't pick it up.

If you use the curse client you may not see the alpha versions. In that case just download manually from wowace.
