### ISSUE TITLE
Trap Launcher [#77769] error in AdiButtonAuras, v2.0-beta-2-9-gb33ffb1

### ISSUE THREAD

**Issue by ghankins** [AdiAddons/AdiButtonAuras#212]
Looks like there is still an old reference to a Hunter spell that was removed.

Date: 2016-07-25 12:33:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiButtonAuras\core\Core.lua line 389:
   Invalid spell identifier: spell:77769
Debug:
   [C]: ?
   AdiButtonAuras\core\RuleDSL.lua:94:
      AdiButtonAuras\core\RuleDSL.lua:89
   AdiButtonAuras\core\RuleDSL.lua:122:
      AdiButtonAuras\core\RuleDSL.lua:121
   AdiButtonAuras\core\RuleDSL.lua:194:
      AdiButtonAuras\core\RuleDSL.lua:193
   [C]: ?
   AdiButtonAuras\core\Core.lua:389: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346:
      ...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308
   (tail call): ?
Locals:
None
AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  NPCScan, v7.0.3.5
  NPCScanOverlay, v7.0.3.4
  NPCScanOverlayBroker, v1.2.6
  Ace3, v
  Acheron, v
  AdiButtonAuras, v2.0-beta-2-9-gb33ffb1
  AdvancedInterfaceOptions, v1.0.2-1-g98e3569
  BanzaiAlert, v2.0
  Bartender4, v4.7.1
  BattlePetBreedID, vv1.6.0
  CanIMogIt, v7.0.3.13
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DeclineDuel, v1.0
  DejaCharacterStats, v7.0.3 r6
  ExRT, v3705
  GatherMate2, v1.36.1
  GTFO, v4.38.3
  GuildDelta, v7.0
  HandyNotes, vv1.4.7
  HandyNotesDraenorTreasures, v1.19a
  HandyNotesLegionRaresTreasures, v0.5
  IskarAssist, v
  JSHB, vv5.1.9
  LibSharedMedia30, v3.0-95
  LoseControl, v5.41
  Masque, v7.0.0
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.144
  MoveAnything, v16.0.3
  NeedToKnow, v4.0.25
  Omen, v3.1.11
  OmniCC, v7.0.1
  Overachiever, v0.84
  Paste, v1.4.7
  Pawn, v2.0.3
  Prat30, v3.6.14      
  Prat30Libraries, v
  Quartz, v3.3.0
  RangeDisplay, vv4.4.0
  SharedMedia, v3.0.7-188
  Skada, v1.4-34
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TidyPlates, v6.18.Beta6
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipTac, v16.07.23
  Titan, v5.7.0.70000
  TitanGold, v5.7.0.70000
  TitanLootType, v5.7.0.70000
  TitanPerformance, v5.7.0.70000
  TitanRepair, v5.7.0.70000
  TomTom, vv70000-1.0.0
  WeakAuras, v2.2.0.8
  ZPerl, v5.0.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidFrames, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=690)

**Comment by Rainrider** [comment]
Could it be that you have some old custom rule with that spell id?

**Comment by ghankins** [comment]
Well duh.  Sorry I thought I checked custom rules before opening the issue.
