### ISSUE TITLE
Error when shapeshifting druid forms

### ISSUE THREAD

**Issue by VanilleGrobi** [AdiAddons/AdiButtonAuras#213]
Hi, I get the below error when shapeshifting my druid into Bear form.
The debug Tooltips do not provide additional information.
In fact I always get 4 errors displayed; I pasted all 4 below.

Hope this helps but if you need any additional information I'd be happy to provide what I can.

Message: Invalid spell identifier: 119403
Time: 07/25/16 20:57:49
Count: 3
Stack: Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:94: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:89>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:122: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:121>
(tail call): ?
Interface\AddOns\AdiButtonAuras\rules\Common.lua:191: in function <Interface\AddOns\AdiButtonAuras\rules\Common.lua:190>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:389: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>
-----------------------------------------------------------------------------------------------------
Message: Invalid spell identifier: 1499
Time: 07/25/16 20:57:49
Count: 3
Stack: Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:94: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:89>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:122: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:121>
(tail call): ?
Interface\AddOns\AdiButtonAuras\rules\Common.lua:191: in function <Interface\AddOns\AdiButtonAuras\rules\Common.lua:190>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:389: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>
---------------------------------------------------------------------------------------------
Message: Interface\SharedXML\SharedUIPanelTemplates.lua:667: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: 07/25/16 20:57:35
Count: 8
Stack: Interface\FrameXML\UIPanelTemplates.lua:96: in function `ScrollingEdit_OnTextChanged'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:604: in function `ScriptErrorsFrame_Update'
...e\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:551: in function `ScriptErrorsFrame_OnError'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:18: in function `_ERRORMESSAGE'
Interface\AddOns\Decursive\Dcr_DIAG.lua:483: in function <Interface\AddOns\Decursive\Dcr_DIAG.lua:380>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...erface\AddOns\AdiBags\libs\BugGrabber\BugGrabber.lua:149: in function <...erface\AddOns\AdiBags\libs\BugGrabber\BugGrabber.lua:147>
...erface\AddOns\AdiBags\libs\BugGrabber\BugGrabber.lua:370: in function <...erface\AddOns\AdiBags\libs\BugGrabber\BugGrabber.lua:292>
(tail call): ?
...
Interface\AddOns\AdiButtonAuras\rules\Common.lua:191: in function <Interface\AddOns\AdiButtonAuras\rules\Common.lua:190>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:389: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>
------------------------------------------------------------------------------------------------
Message: Invalid spell identifier: 60192
Time: 07/25/16 20:57:49
Count: 2
Stack: Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:94: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:89>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:122: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:121>
(tail call): ?
Interface\AddOns\AdiButtonAuras\rules\Common.lua:191: in function <Interface\AddOns\AdiButtonAuras\rules\Common.lua:190>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:389: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>

**Comment by Grimsbain** [comment]
What version are you running? I did a search of the code and didn't see any of those spell ids.

**Comment by Rainrider** [comment]
Yep, it must be an old version. The second error is about an old spellid of Freezing Trap which was removed from DRData in May and was pushed to master the day the pre-patch hit US

**Comment by VanilleGrobi** [comment]
I updated the AddOn this morning using curse client.
The version as reported by the settings UI is: 2.0-beta-2-9-gb33ffb1

Sorry, wanted to add the version with the initial report but forgot it after all the message pasing :(

**Comment by Rainrider** [comment]
Hm, that is the last version, but it seems to contain old data. The download from wowace is ok, I verified that. Maybe a bug with the curse client? I'll try to reproduce.

**Comment by Rainrider** [comment]
I can't reproduce this. The curse client installed fine. No errors when shapeshifting. Maybe some old data was not overwritten or something, I don't know. Please try a clean install. Do not install addons while WoW is running.

**Comment by VanilleGrobi** [comment]
Ok, I went through all the addons, one by one.
It appears that it happens only with "TellMeWhen" (v8.1.1) being installed.
I tried resetting TMW to no avail. 
Next time I'll remember to check with all other addons disabled :-/

**Comment by Rainrider** [comment]
You actually got the error. The guys from TellMeWhen use a version of DRData with old spells but a higher minor than ours. That is why their version gets loaded and overrides our data. This in turn causes ABA to error as it depends on DRData for diminishing returns categories.

Since DRData was removed from wowace/curse, I don't know where they pull from. I'll get to them and try to get this sorted out.

Thank you for your time investigating!

**Comment by Rainrider** [comment]
http://wow.curseforge.com/addons/tellmewhen/tickets/1250-drdata-out-of-sync/ for reference

**Comment by Rainrider** [comment]
I pushed the needed changes to the repo on wowace.
