### ISSUE TITLE
Doesn't work for Arms Warrior, which I see is supported?

### ISSUE THREAD

**Issue by domzzu** [AdiAddons/AdiButtonAuras#216]
Really like this addon, use it as an essential. However upon logging in I am unable to enable? Not sure why, massive addons / interface noob. 

[http://image.prntscr.com/image/829d353175324397895c0bf5f3989684.png](url)

**Comment by domzzu** [comment]
Downloaded the beta version you upaloded on WoWAce, can't get Mortal Strike to show up though? You showed me a way to do it in 2014, however no longer working in that way anymore :(

**Comment by domzzu** [comment]
https://github.com/AdiAddons/LibPlayerSpells-1.0/commit/ec7b8ed9a028e7747410f2a5b695d60dc3b92d3d

Here is my thread from last time, but when I open Warrior lua file now I can't find what I need to change

**Comment by Rainrider** [comment]
This is related to https://github.com/AdiAddons/LibPlayerSpells-1.0/issues/83
Mortal Wounds is applied by multiple classes which appears to be an issue. It will take me some time to track this down, because adding the class data has higher priority for now.

**Comment by domzzu** [comment]
Ofcourse, all your work is appreciated and I understand the priority of other classes. 
Thanks for explanation.

**Comment by Rainrider** [comment]
Should be resolved as of LibPlayerSpells-1.0@ffe8530311d3dcb634e9c14b46aeffdbcc4409f7
