### ISSUE TITLE
No Immolate or Eradication support for locks

### ISSUE THREAD

**Issue by LizardLady** [AdiAddons/AdiButtonAuras#218]
I just downloaded the newest beta version of this addon. It seems that with the changes for Legion, this addon no longer shows the time remaining on Immolate. It always showed it in the past so I'm guessing it must not have been updated for the beta? Also Eradication is a new talent for locks that applies a debuff whenever you use Chaos bolt. It would be nice if this addon also tracked that. My fiance is attempting to make a new "rule" for these but I figured I should let you know for others that may not know how to do this.

**Comment by Rainrider** [comment]
Warlocks have not been added yet. See https://github.com/AdiAddons/LibPlayerSpells-1.0/issues/82

**Comment by LizardLady** [comment]
Oh, sorry! I didn't see that. Just made an account here and I am still not great at finding my way around the site yet. Thanks for letting me know and I can't wait for the updates! I depend on this add on quite a bit (ever since inline aura is no longer) so thanks very much for all the hard work!

**Comment by Rainrider** [comment]
Destruction and affliction should be ready now. Alpha build is coming shortly on wowace/curse
