### ISSUE TITLE
Shadow Priest, Vampiric Touch

### ISSUE THREAD

**Issue by Joshosu420** [AdiAddons/AdiButtonAuras#219]
Looks like Shadow Priests were handled, shadow word pain now has a working timer.  However, looks like vampiric touch is still without a rule.  Bad aura and countdown.

**Comment by Joshosu420** [comment]
Thanks for answering my post.  Could someone maybe post the code i could use to make a custom rule for Vampiric Touch or maybe point out what LUI file the code for Shadow Word: Pain is in. I could copy it and change it into a custom rule for Vampiric Touch.

**Comment by Rainrider** [comment]
Shadow priests should be fully covered now. An alpha build will be pushed to wowace/curse shortly.

**Comment by Joshosu420** [comment]
Thanks for the responses.  Works great.  Appreciated.
