### ISSUE TITLE
Feature request: show buff/debuff remaining time line (instead of text)

### ISSUE THREAD

**Issue by 40P3** [AdiAddons/AdiButtonAuras#220]
Hi,

Love the addon, just recently found it and already on my top10 most favorite personal list. :)

One thing would put the dot up to the i so to speak, is if the remaining time on buff/debuffs would be a graphical line rather than a text. Example like in Diablo 3 on the skill's button there is a line on the top that diminishing as the buff remaining time counts down. Not talking about thinting the whole button! Just a 2-3% thick line (choosable on bottom/top) if bar.

e.g.: This could be a green for buff, red for debuffs on target, yellow for interrupt skills.

Any chance for this? :)

**Comment by Rainrider** [comment]
This should be doable. However I can't give you an ETA on it as there are some other things I'd like to get done and I will hardly have much time in august.

**Comment by 40P3** [comment]
Thanks for the fast replies. I'm very excited that you like the idea.
I will try to be patient. I wouldn't mind even helping... but can't really do coding this much. :(

Keep up the good work!

**Comment by mspykerez** [comment]
This is a pretty interesting concept, I'm eager to try it.
Heres some video for reference on how this works on Diablo3 https://www.youtube.com/watch?v=l-efxpWEsjM

**Comment by mspykerez** [comment]
update: this doesn't seem that hard to implement, there is already another addon called rButtonAura that does it with just a few lines of code. Hopefully we will see it added to AdiButtonAuras soon!

**Comment by Rainrider** [comment]
This is pretty much the bottom of my list of things for ABA. Feel free to make a pull request if it is just a few lines of code.

**Comment by 40P3** [comment]
MY good old ticket. :)
Has it been 4 years already? Crazy!
I don't play WoW now, were you able to implement it or not on your list?
Love(d) this addon so much. :)
