### ISSUE TITLE
Bug on Subtlety Rogue ability Nightblade

### ISSUE THREAD

**Issue by Drewbob01** [AdiAddons/AdiButtonAuras#221]
Hi! Not sure if this is the best way or place to list a bug, and I know this addon takes an enormous effort to update when so many changes have been implemented. I am super-grateful to you all, especially considering after looking through the library files, I realized I am out of my depth. Anyway:

The subtlety rogue ability Nightblade currently has the remaining duration of the subtlety rogue slow debuff Night Terrors displayed on the button rather than the remaining duration of the Nightblade DoT. Although Nightblade does apply Night Terrors, I think overall it would be of greater benefit to have the DoT's duration displayed so that we can know when it needs to be renewed.

Thank you so much! This addon makes a world of difference to my gameplay.

**Comment by Drewbob01** [comment]
Okay, going into the rogue library and simply eliminating the line where Night Terrors tracks to Nightblade seems to do the trick.

I would suggest adding that change to the master file for the sake of future downloads.

Thank you again so much for your effort! Deeply appreciated. :)

**Comment by Rainrider** [comment]
I'll be able to take a look tomorrow as I'm on a trip today. There are a lot of spells providing multiple buffs/debuffs in legion. It also depends on your talent choices and later on learned artifact perks, so I don't have a good way to select for the user what is relevant and what not. You could disable the rules you don't need through the ABA options though or you could write a custom rule to prioritize auras the way that suits you best. You should not edit the lua files as updates will overwrite your changes there.
