### ISSUE TITLE
Resto Shaman Tidal Waves buff

### ISSUE THREAD

**Issue by himlaklar** [AdiAddons/AdiButtonAuras#224]
Heya! 

When I use Riptide, it triggers the tidal waves buff. Tidal waves in turn boosts Healing wave and Healing surge. This is shown correctly by initiating a countdown on those spells. 

However, It also puts another shorter count down on my chain heal spell, despite I cannot find any buff that is significant after using riptide. 

Further more, when I do make use of Tidal Waves, the count down continues on all the buttons even though the buff is gone. 

I added some screenshots : Just after casting riptide; 
![wowscrnshot_081416_171817](https://cloud.githubusercontent.com/assets/21026035/17651251/56867640-6263-11e6-8faa-74852af07279.jpg)

Healing wave to use the buff; 
![wowscrnshot_081416_171819](https://cloud.githubusercontent.com/assets/21026035/17651253/5d0533a8-6263-11e6-987b-13fdd1eeb093.jpg)

Another healing wave after without a buff, still count down on the buttons
![wowscrnshot_081416_171821](https://cloud.githubusercontent.com/assets/21026035/17651255/61959e9e-6263-11e6-9a59-4b7baac6bf91.jpg)

**Comment by Rainrider** [comment]
This is Ancestral Vigor.

To see what rules are enabled:
1. Open ABA options
2. Click on the plus sign
3. Select Spells & items
4. Place your mouse over any of the green overlays on your action buttons

If you click an overlay you can deactivate rules you don't like/need.

I can also disable this completely if it is considered purely useless to track. I just thought maybe someone has use for that timer on pulls or in PvP.

**Comment by himlaklar** [comment]
Thanks. Didn't realize it was the Ancestral Vigor counting down on all of them. A mere misunderstanding :)
