### ISSUE TITLE
addon dont work Error 0000000038A17B20 

### ISSUE THREAD

**Issue by MammonGer** [AdiAddons/AdiButtonAuras#225]
Hello, when im loggin in i got this Error. What can i do?
thanks for the help and sorry for my english ;)

[Error 0000000038A17B20] gefangen, klicke auf den Link für mehr Informationen.
[Error 0000000038A17B20] gefangen, klicke auf den Link für mehr Informationen.
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-12.lua:165: table index is nil
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-12.lua:165: in function `FoundSpell'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-12.lua:205: in function `ScanSpellbook'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-12.lua:268: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:261>
(tail call): ?
self = <table> {
FoundSpell = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:160
IterateSpells = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:152
callbacks = <table> {
}
ScanMasterySpells = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:233
IsKnown = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:116
GetAllIds = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:105
ScanCompanions = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:248
UnregisterAllCallbacks = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
GetBookType = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:128
spells = <table> {
}
ScanFlyout = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:177
RegisterCallback = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
ScanGlyphs = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:219
ScanSpellbook = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:196
UnregisterCallback = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
generation = 2
ScanSpellbooks = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:261
Resolve = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:88
HasSpells = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:310
frame = <unnamed> {
}
}
bookType = "spell"
numSpells = 20
offset = 0
changed = false
(for index) = 1
(for limit) = 20
(for step) = 1
index = 1
spellType = "SPELL"
id1 = 6603
link = "[Automatischer Angriff]"
id2 = nil
name = nil
GetSpellBookItemInfo = <function> defined =[C]:-1
GetSpellLink = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
lib = <table> {
FoundSpell = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:160
IterateSpells = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:152
callbacks = <table> {
}
ScanMasterySpells = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:233
IsKnown = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:116
GetAllIds = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:105
ScanCompanions = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:248
UnregisterAllCallbacks = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
GetBookType = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:128
spells = <table> {
}
ScanFlyout = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:177
RegisterCallback = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
ScanGlyphs = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:219
ScanSpellbook = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:196
UnregisterCallback = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
generation = 2
ScanSpellbooks = <function> defined @Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:261
Resolve = <function> defined @Interfac

**Comment by Rainrider** [comment]
Das sieht nach einer veralteten Version aus. Installiere das Addon von https://www.wowace.com/addons/adibuttonauras/. Du kannst auch den Curse Client zum Updaten verwenden.

You are using an old version. Install the addon from https://www.wowace.com/addons/adibuttonauras/. You can also use the curse client to update.

**Comment by MammonGer** [comment]
I use the curse client and he says its up to date. iI installed the zip folder from wowace but no change. Still the same Error. The LibSpellbook-1.0 is also up to date

**Comment by Rainrider** [comment]
Let the curse client install alpha releases for AdiButtonAuras. If you still have the same error, you didn't install correctly.

**Comment by MammonGer** [comment]
thank you so much, now it works :D
