### ISSUE TITLE
Getting 2 LUA erros on login. 

### ISSUE THREAD

**Issue by nickdekruijk** [AdiAddons/AdiButtonAuras#226]
328x AdiButtonAuras\core\RuleDSL.lua:195: Invalid spell identifier: 114866
[C]: ?
AdiButtonAuras\core\RuleDSL.lua:95: in function <AdiButtonAuras\core\RuleDSL.lua:90>
AdiButtonAuras\core\RuleDSL.lua:123: in function <AdiButtonAuras\core\RuleDSL.lua:122>
AdiButtonAuras\core\RuleDSL.lua:195: in function <AdiButtonAuras\core\RuleDSL.lua:194>
[C]: ?
AdiButtonAuras\core\Core.lua:389: in function `?'
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

And:

328x AdiButtonAuras\core\RuleDSL.lua:195: Invalid spell identifier: 130735
[C]: ?
AdiButtonAuras\core\RuleDSL.lua:95: in function <AdiButtonAuras\core\RuleDSL.lua:90>
AdiButtonAuras\core\RuleDSL.lua:123: in function <AdiButtonAuras\core\RuleDSL.lua:122>
AdiButtonAuras\core\RuleDSL.lua:195: in function <AdiButtonAuras\core\RuleDSL.lua:194>
[C]: ?
AdiButtonAuras\core\Core.lua:389: in function `?'
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals:
nil

**Comment by nickdekruijk** [comment]
Never mind. Was a user rule that was from previous expansion....

**Comment by wsuhoey** [comment]
Side note, I found that the Soul Reaper error for Spell Identifier 114866 was caused by a user SAMPLE rule that was auto-generated by clicking the New Rule button. After deleting the rule and re-starting the game, the error went away. tl;dr: check your user rules for template rules that you may not be using.
