### ISSUE TITLE
LUA Error only on my Shaman on login

### ISSUE THREAD

**Issue by Marroque** [AdiAddons/AdiButtonAuras#228]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0

#### How did you install the addon (curse client/manually)?
Curse Client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Shaman
  - Your spec: Enhancement
  - Name of the spell (and spell id if known): N/A
  - Source of the spell (core ability/talent/artifact/pvp): N/A

#### If you have an error report, copy it below:
Message: Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:195: Invalid spell identifier: 114866
Time: 08/22/16 02:33:29
Count: 1
Stack: Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:95: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:90>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:123: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:122>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:195: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:194>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:389: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>

**Comment by Rainrider** [comment]
See #226. It is a custom rule about soul reaper
