### ISSUE TITLE
Spell Flash - Spell Missing option Bug

### ISSUE THREAD

**Issue by Smittius** [AdiAddons/AdiButtonAuras#230]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?

2.0

#### How did you install the addon (curse client/manually)?

Curse Client

#### If using the curse client, what type of release did you install (alpha/beta/release)?

Not sure

#### If you installed manually, where did you download the addon from?

Curse

#### Which type of installation did you choose (nolib/normal)?

Curse

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:
  - Your spec:
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below:

There is a severe conflict between functionality of the "Show Missing>Show Flash" drop-down and the "No Flash on Cooldown" check-box.  

If you set a spell to "Show Missing> Show Flash", as soon as you enter combat, that spell lights up as it should.  Once you use that spell and apply either a debuff or self-buff, and put the spell on cooldown, the box colors per the style of debuff/buff, and it shows the spell timer, again as it should.  

Unfortunately, once that ability comes off CD, the button DOES NOT LIGHT UP, whether the spell has a duration for a buff or debuff or otherwise.  It appears the conflict arises from casting a spell with a timed CD which puts that spell on cool-down, which in turns off the Spell Flash.  Once that ability finishes it's cooldown, and becomes usable again, the Spell Flash DOES NOT LIGHT UP, even though the criteria for that particular spell flash are met.

Essentially, with the current configuration, I set Dragon Roar to show Spell Flash whenever the Dragon Roar buff is MISSING.  As soon as I enter combat, Dragon Roar lights up from Spell Flash telling me its ready to fire off, which I do.  From that point on, Dragon Roar will NOT Spell Flash again for the remainder of that fight (I think it resets out of combat, but thats kind of irrelevant to this report).  The details are, when dragon roar self-buff fades, the spell will still be on cooldown, so it tells Spell Flash not to show up.  Once it finish it's cooldown, nothing happens.

**Comment by Smittius** [comment]
I've noticed other issues getting responses, yet no comments here.  Is this something that isn't going to get addressed anytime soon?  Please at least acknowledge so I can stop checking this post all the time.

**Comment by Rainrider** [comment]
Other open issues took less time to fix or were affecting more users, so they got attention first. Yours will sadly take me some time as I have to check quite a lot of code to identify the problem.

There is no need to check here constantly, you should get a notification when there is progress.

**Comment by Smittius** [comment]
Thanks Rainrider for the response.  First time using this forum, and i was not aware that I would get emails up response... I will refrain from pestering again.  Typically if an add-on doesn't work they way I like I just find a new add-on, but AdiButtonAuras is unique and relevant enough to warrant providing feedback.  Phenomenal add-on.
