### ISSUE TITLE
Prot Pally

### ISSUE THREAD

**Issue by Krazy74** [AdiAddons/AdiButtonAuras#236]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.1

#### How did you install the addon (curse client/manually)?
Curse client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### If you installed manually, where did you download the addon from?
N/A

#### Which type of installation did you choose (nolib/normal)?
Assuming Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Pally
  - Your spec: Prot
  - Name of the spell (and spell id if known): Rebuke(96231) Avenger's Shield(31935) Hammer of Justice(853)
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below: No error

Currently I do not see the light up for the prot spec. Currently it is the only spec I am playing and do not know if the other specs are working. Before Legion, the rebuke and Avenger's shield will light up for interrupting. Hammer of Justice would show a timer for a stun if I have stunned it or fade it if someone else did. None of this is currently working. I am not sure if anything is not working due to the changes of the class but it may need a little attention or maybe I am just missing something. 

Thank you for your help and one of my favorite addons. I promote this addon all the time.

**Comment by Rainrider** [comment]
This is strange, all 3 work as expected for me.

Rebuke: Flashes if the target is casting an interruptible spell
Avenger's Shield: Flashes if the target is a non-player and is casting an interruptible spell
Hammer of Justice: Shows the bad border + duration for all stuns. (is has never faded if someone else applied anything to it.)

Any errors? What happens when your type /aba in-game? Does the configuration screen come up?

**Comment by Krazy74** [comment]
Thanks for getting back to me. I do not know what I did but after I sent the message, I messed around with another character and it worked with that character, went back to my pally and it started working. Sorry to bother you and again thanks for getting back to me so quickly.
