### ISSUE TITLE
Error on loadin

### ISSUE THREAD

**Issue by allcoast** [AdiAddons/AdiButtonAuras#237]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
Latest

#### How did you install the addon (curse client/manually)?
Curse

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:  Hunter
  - Your spec: All
  - Name of the spell (and spell id if known): Bug
  - Source of the spell (core ability/talent/artifact/pvp): na

#### If you have an error report, copy it below:
10x ...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-8.lua:196: 'for' limit must be a number
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-8.lua:196: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:194>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-8.lua:330: in function `?'
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-8.lua:68: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals:
artifactID = nil
relics = <table> {
}
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
GetNumRelicSlots = <function> defined =[C]:-1
GetRelicSlotType = <function> defined =[C]:-1
GetRelicInfo = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
artifacts = <table> {
 knowledgeMultiplier = 1
 128940 = <table> {
 }
 knowledgeLevel = 0
}

**Comment by Rainrider** [comment]
Please follow https://github.com/Rainrider/LibArtifactData-1.0/issues/4
