### ISSUE TITLE
Coagulated Nightwell Residue Trinket

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiButtonAuras#238]
This trinket doesnt have an automatic rule for it. Its a highly rated tank trinket.
It would be nice if when you had the trinket on your bar it showed the current stacks of the trinket so you have an idea of how much of a shield you will get when you use it.

http://www.wowhead.com/item=137400/coagulated-nightwell-residue&bonus=1727

**Comment by Rainrider** [comment]
@Adirelle could you run the scanner for LIB please, I still don't have php on my machine :)

**Comment by arcadepro** [comment]
The trinket has been added but I'll just post a quick user rule I was using before the fix.

```
return Configure {
    "Nightwell Energy",
    L["Shows stacks of Nightwell Energy and flashes at max."],
    "item:137400",
    "player",
    "UNIT_AURA",
    function(_, model)
        local found, count = GetPlayerBuff("player", 214572)
        if  found then
            model.count = count
            if count > 9 then
                model.hint = true
            end
        end
    end,
}
```
