### ISSUE TITLE
Hunter and Paladin modules out of date?

### ISSUE THREAD

**Issue by mechaninja** [AdiAddons/AdiButtonAuras#241]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?

2.0.3
#### How did you install the addon (curse client/manually)?

curse client
#### If using the curse client, what type of release did you install (alpha/beta/release)?

release, also checked for beta and alpha
#### Which type of installation did you choose (nolib/normal)?

Whichever one Curse does automatically; I didn't choose.
#### If your report is about a missing or wrong spell provide the following information:

Happens on my DH and my rogue.
#### If you have an error report, copy it below:

Two reports: 

```
LibPlayerSpells-1.0-9: 3 errors in PALADIN database:
Data are probably outdated: data version=70000, client version=70100
Spell #202270: unknown spell
Spell #205656: unknown provider spell
...uttonAuras\libs\LibPlayerSpells-1.0-9\data\Paladin.lua:23 in main chunk

Locals:
nil

```

also:

```
LibPlayerSpells-1.0-9: 4 errors in HUNTER database:
Data are probably outdated: data version=70000, client version=70100
Spell #204321: unknown spell
Spell #204324: unknown spell
Spell #204333: unknown spell
...ButtonAuras\libs\LibPlayerSpells-1.0-9\data\Hunter.lua:23 in main chunk

Locals:
nil
```

**Comment by Rainrider** [comment]
Fixed in https://github.com/AdiAddons/LibPlayerSpells-1.0/issues/110
