### ISSUE TITLE
Sheilun Gift, Rules about GetSpellCharge

### ISSUE THREAD

**Issue by j3rem1e** [AdiAddons/AdiButtonAuras#242]
It's not really an issue, but I am looking for help to create a rule about the mistweaver artifact, Sheilun's Gift. The rule is simple, I want the button to flash when the charge are greater than 6.

However, I don't know the best way to write such rule : as the trigger is the amount of "GetSpellCharge",  what event should I bind in order to active this kind of rule rule ? I have seen weakauras using "COMBAT_LOG_EVENT_UNFILTERED" and using *_DOSE filters, but I don't know if it's possible/performant to have a AdiButtonAuras rules with this event.

**Comment by Rainrider** [comment]
Combat log events won't do. We don't pass event arguments to the handlers so you won't be able to filter those. Also GetSpellCharges(205406) returns only nil for me regardless of how many changes the spell has. I don't know how such a rule would be possible with ABA, I'm sorry.

**Comment by j3rem1e** [comment]
Thanks. My mistake, it's GetSpellCount(), not GetSpellCharge()

**Comment by Rainrider** [comment]
I that case you could try UNIT_HEALTH for the "ally" unit or UNIT_POWER for "player". They fire often enough to be close enough on the charges. I'll have to add GetSpellCount to the secure environment though.

**Comment by Rainrider** [comment]
I pushed the changes, an alpha build will be available shortly on wowace.com

**Comment by j3rem1e** [comment]
Thanks. This rule seems to work : 

```
return Configure {
  "SheilunGift",
  "Flash SheilunGift when charge >= 6",
  205406,
  "player",
  { "UNIT_POWER","UNIT_SPELLCAST_START","UNIT_SPELLCAST_STOP" },
  function(units, model)
        if GetSpellCount(205406) > 5 then
            model.highlight = "flash"
        end
    end
}
```
