### ISSUE TITLE
Patch 7.1.5 and ABA 2.0.4

### ISSUE THREAD

**Issue by Golheart** [AdiAddons/AdiButtonAuras#244]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.4

#### How did you install the addon (curse client/manually)?

curse
#### If using the curse client, what type of release did you install (alpha/beta/release)?

release
#### If your report is about a missing or wrong spell provide the following information:
  - Your class: priest
  - Your spec: shadow
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below:
13x Invalid spell identifier: 7321
[C]:: ?
AdiButtonAuras\core\RuleDSL.lua:97: in function <AdiButtonAuras\core\RuleDSL.lua:92>
AdiButtonAuras\core\RuleDSL.lua:125: in function <AdiButtonAuras\core\RuleDSL.lua:124>
AdiButtonAuras\core\RuleDSL.lua:197: in function <AdiButtonAuras\core\RuleDSL.lua:196>
[C]:: ?
AdiButtonAuras\core\Core.lua:388: in function '?'
...ras\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ras\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]:: ?
[string "safecall Dispatcher[1]"]:13: in function '?'
...ras\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function 'Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

**Comment by Rainrider** [comment]
A build fixing this is pending review on curse.com currently. It will be an alpha version once it passes.

Class data has not been updated yet.
