### ISSUE TITLE
Patch 7.1.5 Support

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/AdiButtonAuras#245]
Progress:
  - [x] Death Knight
  - [x] Demon Hunter
  - [x] Druid
  - [x] Hunter
  - [x] Mage
  - [x] Monk
  - [x] Paladin
  - [x] Priest
  - [x] Rogue
  - [x] Shaman
  - [x] Warlock
  - [x] Warrior

**Comment by arcadepro** [comment]
I don't have anything setup on this PC right now but I have an updated Warrior.lua for LibPlayerSpells/Data here https://gist.github.com/arcadepro/da14298283e84917a8c2ccf555ac94cc if you want to save a little time.

**Comment by Rainrider** [comment]
Thank you!
