### ISSUE TITLE
Seal of Light (202273) removed in 7.1.5, still referenced in AdiButtonAuras

### ISSUE THREAD

**Issue by Sabin1936** [AdiAddons/AdiButtonAuras#246]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.5

#### How did you install the addon (curse client/manually)?
curse

#### If using the curse client, what type of release did you install (alpha/beta/release)?
release

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Paladin
  - Your spec: Retribution
  - Name of the spell (and spell id if known): Seal of Light, id 202273
  - Source of the spell (core ability/talent/artifact/pvp): no longer exists in 7.1.5

**Comment by Marroque** [comment]
Lua Error:
Message: ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: Invalid spell identifier: 202273
Time: 01/14/17 01:57:17
Count: 4
Stack: [C]: ?
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:97: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:92>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:125: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:124>
Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:197: in function <Interface\AddOns\AdiButtonAuras\core\RuleDSL.lua:196>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:388: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals: <none>

**Comment by Rainrider** [comment]
Sorry about that, fixes with latest push.
