### ISSUE TITLE
Packaged Version 2.0.6 - Older LibPlayerSpells-1.0?

### ISSUE THREAD

**Issue by IngeniousDox** [AdiAddons/AdiButtonAuras#248]
Hello! I'm have been using AdiButtonAuras (and InlineAura before that) for years, and I'm loving it. Since Legion I have noticed some issues with certain spells not being added yet, leaving certain classes incomplete, esp on the honor talents part. I fully understand that Legion made for a lot of changes, and playing alts has simply become harder. Testing and grinding out honor talents on every class is not fast. So I'm looking to see if I can squeeze out some time to fill in some of the blank spots.

Even though I can change a LUA file without issues, I hadn't really looked into WoW addon developement before. I figured I could clone the addon and the various libs to my addon directory, then simply make the changes and test them ingame, then submit the PRs. But this isn't as straightforward as I thought, with the deployed addon being build by Curse with the help of the info in .pkgmeta in the source, etc. I'll look into this more when I next have time.

However I did come across one thing that caught my eye. The version of LibPlayerSpell-1.0 that is packaged with 2.0.6 seems to be an older version compared to both Git and the version that is available on Curse/WoWAce to download directly. This older version is missing the 7.1.5 changes. Perhaps it might be handy to submit a new build to Curse?

Cheers,

Dox

**Comment by Rainrider** [comment]
Good catch, thank you.

As for the honor talents, please take a look at https://github.com/AdiAddons/LibPlayerSpells-1.0/issues/99

**Comment by IngeniousDox** [comment]
I have seen that. I considered giving the info and let you fix it. But there still is a lot to do. So if I could set up myself, then I can just fix / add stuff and give you the PRs, I figure it will save us both time in the long run.

Plus, I like to tinker. Right now I'm using 2.0.4 with my own modifications, I think I have around 15. So my next step will just be installing 2.0.7. Seeing which of my modifications are still needed. I'll take it from there. My changes are in Common.lua "Snares and Anti-Snares" section of the main addon, and in LibPlayerSpell. When I have time, I'll see what I can PR.

Setting up the up the addon with cloning didn't work, but I'll just install the addon from Curse, and symlink the files I will be changing to the corresponding files in the clones the repos. Then I should be able to give you PRs for my changes.
