### ISSUE TITLE
Custom ShowStacks works only once during combat

### ISSUE THREAD

**Issue by Fablezim** [AdiAddons/AdiButtonAuras#249]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.6

#### How did you install the addon (curse client/manually)?
Curse

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### If you installed manually, where did you download the addon from?
N/A

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Demon Hunter
  - Your spec: Havoc
  - Name of the spell (and spell id if known): 211053 (Fel Barrage)
  - Source of the spell (core ability/talent/artifact/pvp): Talent

#### If you have an error report, copy it below:

No error report. I made a custom rule for Fel Barrage to only flash when it hits 5 stacks. I am new to this aspect of AdiButtonAuras but after an hour or so I got this to work:

ShowStacks {
    211053, -- Fel Barrage
    5,
    "player",
    "flash"
}

The issues is it only works ONCE during a combat cycle- when I use it after the 5 and flash and get it back to 5 again, it doesn't flash. Once I exit combat and restart, it will flash the first time but no longer afterwards. I'm guessing its something odd with my code since again, I'm a noob. Can you help??

**Comment by Fablezim** [comment]
...I added "return" before my code and it works now. Durp. Sorry to waste the space here haha.

**Comment by Fablezim** [comment]
Still acting a bit wonky though so any advice would still be appreciated :)

**Comment by Rainrider** [comment]
Sorry, this one slipped through. "Wonky" is not specific enough though :)
