### ISSUE TITLE
some bug occuring infight

### ISSUE THREAD

**Issue by Pandha** [AdiAddons/AdiButtonAuras#251]
Hello,
I dont know from what this bug is coming. But it occurs while I fight bosses. I dont see any wrong behavior, but infight i doesnt have enough time to look at it :)
It is a bit annoying, because i get really often:

[21:02] There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.

#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.6

#### How did you install the addon (curse client/manually)?
curse client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
beta

#### If you installed manually, where did you download the addon from?
-

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Warrior
  - Your spec: Fury
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below:

168487x [string "return Configure {..."]:23: Invalid expiration, should be a number, not boolean
[C]: ?
AdiButtonAuras\core\Overlays.lua:446: in function <AdiButtonAuras\core\Overlays.lua:443>
[string "return Configure {..."]:23: in function `handler'
AdiButtonAuras\core\Overlays.lua:479: in function <AdiButtonAuras\core\Overlays.lua:469>

Locals:

**Comment by Rainrider** [comment]
Do you by chance have any custom rules?

**Comment by Pandha** [comment]
Yes, indeed.

```
return Configure {

    -- Unique Id
    "Wutanfall",

    -- Description
    "Blutdurst leuchtet, wenn Wutanfall",

    -- Spells to modify
    23881, -- Blutdurst

    -- Unit(s) to watch
    "player",

    -- Event(s) to watch
    "UNIT_AURA",

    -- Callback
    function(units, model)
        if GetPlayerBuff("player", 184362) -- buff Wutanfall
        then
            model.hint = true
            model.expiration = true
        end
    end

}
```

```
return Configure {

    -- Unique Id
    "Klingensturm",

    -- Description
    "Klingensturm wird ausgegraut, wenn nicht wütend",

    -- Spells to modify
    46924, -- Klingensturm

    -- Unit(s) to watch
    "player",

    -- Event(s) to watch
    "UNIT_AURA",

    -- Callback
    function(units, model)
        if not GetPlayerBuff("player", 12880) -- buff Wutanfall
        then
            model.highlight = "darken"
        end
    end

}
```

```
return Configure {

    -- Unique Id
    "Revenge",

    -- Description
    "Revenge, Vengeance: Revenge",

    -- Spells to modify
    6572, -- Revenge

    -- Unit(s) to watch
    "player",

    -- Event(s) to watch
    "UNIT_AURA",

    -- Callback
    function(units, model)
        if GetPlayerBuff("player", 202573) -- buff Vengeance: Revenge
        then
            model.highlight = "good"
        end
    end

}
```

**Comment by Rainrider** [comment]
The error is caused by your first rule - `model.expiration` should be a number (the 3rd return of `GetPlayerBuff`').
Apart from that your first and third rules are now included in ABA through LibPlayerSpells, so you don't need them anymore. Also the spell id 12880 has been removed from the game, so your second rule is useless.
