### ISSUE TITLE
Packaged LibArtifactData is broken on 7.2 PTR

### ISSUE THREAD

**Issue by Sipollo** [AdiAddons/AdiButtonAuras#252]
In the current packaged version of AdiButtonAuras, the included LibArtifactData is causing LUA errors:

3x FrameXML\MainMenuBar.lua:125: Usage: local cost = C_ArtifactUI.GetCostForPointAtRank(rank, tier)
[C]: in function `GetCostForPointAtRank'
FrameXML\MainMenuBar.lua:125: in function <FrameXML\MainMenuBar.lua:123>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:232: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:223>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:262: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:254>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:273: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:270>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:314: in function `?'
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:68: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals:
(*temporary) = 13
(*temporary) = nil

**Comment by Rainrider** [comment]
This should be addressed by https://github.com/Rainrider/LibArtifactData-1.0/commit/0a5024c8fd971c6009083e8b29b12a8fc5d47909
