### ISSUE TITLE
Invalid Spell Identifier as Affliction Warlock

### ISSUE THREAD

**Issue by staratnight** [AdiAddons/AdiButtonAuras#253]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
Version 2.0.8

#### How did you install the addon (curse client/manually)?
Installed via Curse (Twitch) client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
beta

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: **Warlock**
  - Your spec: **Affliction**
  - Name of the spell (and spell id if known):
I don't know... messages I get:
_Invalid spell identifier: 114866
Invalid spell identifier: 130735_
  - Source of the spell (core ability/talent/artifact/pvp):
--
#### If you have an error report, copy it below:
I have two...
First: 
> 292x AdiButtonAuras\core\RuleDSL.lua:197: Invalid spell identifier: 130735
[C]: ?
AdiButtonAuras\core\RuleDSL.lua:97: in function <AdiButtonAuras\core\RuleDSL.lua:92>
AdiButtonAuras\core\RuleDSL.lua:125: in function <AdiButtonAuras\core\RuleDSL.lua:124>
AdiButtonAuras\core\RuleDSL.lua:197: in function <AdiButtonAuras\core\RuleDSL.lua:196>
[C]: ?
AdiButtonAuras\core\Core.lua:388: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?
Locals:
nil

Second:
> 292x AdiButtonAuras\core\RuleDSL.lua:197: Invalid spell identifier: 130735
[C]: ?
AdiButtonAuras\core\RuleDSL.lua:97: in function <AdiButtonAuras\core\RuleDSL.lua:92>
AdiButtonAuras\core\RuleDSL.lua:125: in function <AdiButtonAuras\core\RuleDSL.lua:124>
AdiButtonAuras\core\RuleDSL.lua:197: in function <AdiButtonAuras\core\RuleDSL.lua:196>
[C]: ?
AdiButtonAuras\core\Core.lua:388: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?
Locals:
nil

**Comment by Rainrider** [comment]
Hi and sorry for taking so long to reply.

Both of the provided spell ids refer to old versions of Soul Reaper for Blood and Frost Death Knights which were removed with Legion. Both spells are referenced in an example user rule which you seem to have activated for your warlock. This is why you get this error.

Please deactivate the user rule to stop getting this error. I will update the example in a future release of ABA.
