### ISSUE TITLE
Spell request: Solar Beam

### ISSUE THREAD

**Issue by eliot22** [AdiAddons/AdiButtonAuras#254]
Please add a spell-interrupt aura for "Solar Beam" for Balance Druid. I love how the interrupt ability button lights up for other classes when the target is casting an interruptible spell. For example, "Wind Shear" for Shamans, "Pummel" for Warriors, and "Kick" for Rogues.

Thank you.

**Comment by Rainrider** [comment]
Updated versions of LPS and ABA should be up shortly. Thanks for reporting
