### ISSUE TITLE
Add support for Al'maiesh, the Cord of Hope

### ISSUE THREAD

**Issue by temporicide4** [AdiAddons/AdiButtonAuras#255]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.9-4-g7deeb85

#### How did you install the addon (curse client/manually)?
Curse Client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Alpha

#### Which type of installation did you choose (nolib/normal)?
Normal

The Holy Priest legendary item Al'maiesh, the Cord of Hope gives stacking buffs on the priest that empowers the Holy Word spells. Each of the three Holy Word spells has its own buff, which stacks to 5 and has infinite duration.

I created a custom rule to show these buffs on the respective Holy Word spells, but I think this rule should be added to the built-in rulesets.

```
return {
  -- Holy Word: Serenity
  SelfBuffAliases { 2050, 211440, },
  -- Holy Word: Sanctify
  SelfBuffAliases { 34861, 211442, },
  -- Holy Word: Chastise
  SelfBuffAliases { 88625, 211443, }
}
```

**Comment by Rainrider** [comment]
Thank you very much! I'll see into adding this tomorrow.
