### ISSUE TITLE
New LUA Error since today

### ISSUE THREAD

**Issue by nickdekruijk** [AdiAddons/AdiButtonAuras#256]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.10

#### How did you install the addon (curse client/manually)?
Twitch client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
release (alpha version is the same)

#### Which type of installation did you choose (nolib/normal)?
normal I think

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: druid
  - Your spec: balance
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/artifact/pvp):

I think it has to do with this ring: http://www.wowhead.com/item=142173/ring-of-collapsing-futures&bonus=1826:1457
Was hoping your addon would show the debuff you get when you use the ring. But since I tried that I'm getting these errors. Reinstalling the addon, resetting profile or deleting AdiButtonAuras.lua from SavedVariables didn't help

#### If you have an error report, copy it below:

[14:06:30] [ADDON_ACTION_BLOCKED] AddOn 'FactionAddict' tried to call the protected function 'CompactPartyFrameMember1:Show()'.
[14:06:30] ...AddOns\AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573: in function <...AddOns\AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
Interface\FrameXML\CompactUnitFrame.lua:342: in function `CompactUnitFrame_UpdateVisible'
Interface\FrameXML\CompactUnitFrame.lua:283: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:117: in function <Interface\FrameXML\CompactUnitFrame.lua:53>
[14:06:30] InCombatSkipped
[14:06:33] ...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:210: bad argument #1 to 'strmatch' (string expected, got nil)
[14:06:33] [C]: ?
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:210: in function `ScanSpellbook'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:315: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?
[14:06:33] (*temporary) = nil
(*temporary) = "spell:(%d+):%d+%[(.+)%]"
(*temporary) = "string expected, got nil"

(Your addon comes with buggrabber which only works half, 'click on the link for more information' doesn't work for me)

**Comment by nickdekruijk** [comment]
I just noticed I'm only getting the errors while on Argus. Maybe it's because I use the Warframe Vindicaar power and not the Light's Judgement anymore. When I switch back to Light's Judgement the error is gone!

**Comment by Dudditz** [comment]
Getting the same error from Adi. Disabled all other addons to verify.

300x ...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:210: bad argument #1 to 'strmatch' (string expected, got nil)
[C]: ?
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:210: in function `ScanSpellbook'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:315: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?

Locals:
(*temporary) = nil
(*temporary) = "spell:(%d+):%d+|h%[(.+)%]"
(*temporary) = "string expected, got nil"

**Comment by Rainrider** [comment]
It seems a spell from the spellbook did not provide a link. I'm halfway through the chapter 2 quest line, I think I'll be able to look into the issue tonight.

**Comment by Rainrider** [comment]
`GetSpellLink` returns nil for "Summon Lightforged Warframe". Shift-clicking the spell icon in the spell book does not produce a chat link either. This is a Blizzard bug, but it is now taken care of. Thank you for submitting the issue and nailing down the cause!
