### ISSUE TITLE
C_Timer:After duration is too large

### ISSUE THREAD

**Issue by speedwaystar** [AdiAddons/AdiButtonAuras#258]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.11

#### How did you install the addon (curse client/manually)?
Twitch

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Alpha

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If you have an error report, copy it below:
4x AdiButtonAuras\core\Overlays.lua:380: C_Timer.After duration is too large
[C]: in function `After'
AdiButtonAuras\core\Overlays.lua:380: in function `UpdateCooldown'
AdiButtonAuras\core\Overlays.lua:250: in function <AdiButtonAuras\core\Overlays.lua:245>
(tail call): ?

Locals:
(*temporary) = 4295361.88
(*temporary) = <function> defined @AdiButtonAuras\core\Overlays.lua:380

**Comment by Rainrider** [comment]
I'll need some time to investigate, it seems some spell on your action bars has a __huge__ cooldown. It would be helpful if you could help me reproduce the issue.

**Comment by speedwaystar** [comment]
let me see if it recurs. it may have been on a specific toon since I
haven't seen the error since posting

**Comment by Zephimere** [comment]
So I'm getting this issue as well, the only item on my bars that has a long cooldown that I've noticed is the green quality Shroud of Cooperation, tullacc is saying it has a 50 day cooldown for whatever reason.
