### ISSUE TITLE
Errror on logging out on 7.3.2

### ISSUE THREAD

**Issue by HolgerDKz** [AdiAddons/AdiButtonAuras#260]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.11

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Twitch client, release

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: 
  - Your spec: 
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'WorldBossStatus' tried to call the protected function 'oldLogout()'.
AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573: in function <AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573>
[C]: in function `oldLogout'
WorldBossStatus\WorldBossStatus-5.6.lua:1637: in function `Logout'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
[C]: ?

Locals:
nil

**Comment by Rainrider** [comment]
This is a problem with WorldBossStatus, not with ABA. You see ABA mentioned there because it embeds BugGrabber.
