### ISSUE TITLE
Death Strike Suggestion

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiButtonAuras#261]
Just putting this out there.... As a blood death knight, knowing how much my DS will heal me for is super important. Any chance to show an estimated % of my health to be healed on it?

**Comment by Rainrider** [comment]
Not without tracking the combat log. This is out of scope for ABA. There was https://github.com/sunaurus/ElvUI_TankHealth but it is poorly coded and abandoned.

**Comment by yajinni** [comment]
Closing my issue since it doesnt seem within the scope of the project.
