### ISSUE TITLE
Issues creating/deleting custon rules.

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiButtonAuras#262]
I created the following rule:

```
return ShowStacks {
    195182, --Marrowrend
    195181, -- Bone Shield (stacking buff)
    10,
    "player",
    -6,
    "flash",
}
```
Yet it doesnt seem to work and when i click on marrowrend it doesnt show up as a possible rule. Earlier attempts to create rules do. And nothing i do seems to get rid of them. Uninstalled and deleted the variable file. But once i recreate the above rule the old ones reappear. I have no idea whats going on...

![image](https://user-images.githubusercontent.com/9600587/34466793-c5bc7e6a-eead-11e7-9ff6-9bf1fd0e827f.png)

![image](https://user-images.githubusercontent.com/9600587/34466795-d36bdd26-eead-11e7-89e8-6ed65743c5d8.png)

**Comment by Rainrider** [comment]
ABA comes with a big set of predefined rules. There is a predefined rule for Marrowrend showing the stacks and remaining duration of Bone Shield.

In your first screenshot you see that both rules are enabled. The one that comes with ABA has [LPS DEATHKNIGHT-7.3.0-1] at the end of its description. Your custom rule is resolved into two rules: one for the stack count and one for the flash. You can disable whichever rule you want by clicking on it.

There is no way to remove the predefined rules without editing ABA's code and I strongly recommend against that. Just disable the ones you dislike from the options panel. Deleting the saved variables file will remove all custom rules and all your preferences (like which predefined rules you disabled).

If you want your rule to flash even out of combat, disable the "No flash out of combat" option.

**Comment by yajinni** [comment]
Oh ok. I guess i was confused. I didnt realise it split it into 2 things. I would have thought it would make it into 1 rule.  I thought those were old ones i had created before because thier names were similar to the ones i made before. Sorry for the confusion. Will check a few things and will close if all seems good.

**Comment by yajinni** [comment]
Thanks for clearing that up. Like i said it seems i was mistaken in what was happening. All works perfect now. Closing. Thanks!
