### ISSUE TITLE
How to do multiple charges

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiButtonAuras#263]
I have this spell: http://www.wowhead.com/spell=50842/blood-boil
It has 2 charges to it. How would i go about making a custom that makes the button flash  if it currently has 2 charges to remind me to burn one charge?
No idea where to start on this one.

**Comment by Rainrider** [comment]
Create a custom rule with the following body:
```lua
return Configure {
	'BloodBoilCharges',
	'Flash Blood Boil when it has more than 1 charges.',
	50842,
	'player',
	'SPELL_UPDATE_CHARGES',
	function(_, model)
		local numCharges = GetSpellCharges(50842)
		if numCharges > 1 then
			model.flash = true
		end
	end,
}
```
