### ISSUE TITLE
Sunfire wrong cooldown

### ISSUE THREAD

**Issue by mixMugz** [AdiAddons/AdiButtonAuras#266]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2..0.13

#### How did you install the addon (curse client/manually)?
Curse and manuale. Same shit

#### If using the curse client, what type of release did you install (alpha/beta/release)?
release

#### If you installed manually, where did you download the addon from?
from git

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Druid
  - Your spec: Moonkin
  - Name of the spell (and spell id if known): Sunfire, id: 
  - Source of the spell (core ability/talent/artifact/pvp): core

#### If you have an error report, copy it below:
No error. Always showing cooldown starting from 9 and countdown. Then always reseting to 9 state.

**Comment by Rainrider** [comment]
Maybe it is showing [Circadian Invocation](http://www.wowhead.com/spell=240607/circadian-invocation).

1. Type /aba in chat
2. Click Spells & Items
3. Click on Sunfire on your action bar
4. Deactivate the rules you don't want shown

**Comment by mixMugz** [comment]
I want to show my sunfire.

**Comment by mixMugz** [comment]
Dominos Bufftimers show correct timing. AdiButtonAuro not correct

**Comment by Rainrider** [comment]
Just try to follow this: https://github.com/AdiAddons/AdiButtonAuras/issues/265#issuecomment-357690508
