### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by bucihost** [AdiAddons/AdiButtonAuras#270]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
AdiButtonAuras-2.0.13

#### How did you install the addon (curse client/manually)?
Manually

#### If you installed manually, where did you download the addon from?
Curse

#### Which type of installation did you choose (nolib/normal)?

normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Druid
  - Your spec: Feral
  - Name of the spell (and spell id if known): -
  - Source of the spell (core ability/talent/artifact/pvp): -

#### If you have an error report, copy it below:
[17:29:57] ...AddOns\AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573: in function <...AddOns\AdiButtonAuras\libs\BugGrabber\BugGrabber.lua:573>
[C]: in function `originalShow'
Interface\FrameXML\FrameLocks.lua:97: in function <Interface\FrameXML\FrameLocks.lua:75>
Interface\FrameXML\FrameLocks.lua:110: in function <Interface\FrameXML\FrameLocks.lua:103>
Interface\FrameXML\FrameLocks.lua:132: in function `Show'
Interface\FrameXML\TargetFrame.lua:111: in function `TargetFrame_Update'
Interface\FrameXML\TargetFrame.lua:160: in function `OnEvent'
Interface\FrameXML\UnitFrame.lua:921: in function <Interface\FrameXML\UnitFrame.lua:919>
[C]: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:346: in function `handler'
Interface\FrameXML\SecureTemplates.lua:619: in function `SecureActionButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>
[17:29:57] InCombatSkipped

**Comment by Rainrider** [comment]
I can't tell how this relates to ABA. ABA has an embedded version of BugGrabber, which is a bug reporting addon. This is why you see AdiButtonAuras in the error message. Also the report is truncated. Install BugSack if you want to see and paste me the full bug report. Also try to find a reliable way to reproduce the problem and share your findings here.
