### ISSUE TITLE
Possible performance issues.

### ISSUE THREAD

**Issue by arcadepro** [AdiAddons/AdiButtonAuras#272]
This is not a bug as such but having recently done some testing on which addons affect my fps in raids I was surprised to find that AdiButtonAuras was a bit of a hog.

The addon 'Addon CPU Usage' confirmed it but I'm unsure how reliable it is. Addon profiling in WoW is a bit nebulous but there was a visible difference with ABA on/off for the same encounter. 

Whether it's caused by the act of reading the combat log events, scanning the buffs or drawing the overlays I have no idea. Maybe add an option to track only buffs on the player to test?

I just thought I'd flag it up as something that might need attention.

**Comment by Rainrider** [comment]
While there is certainly something that can be optimized, I would expect some above average CPU usage given the tasks ABA performs. UNIT_AURA is the main source of information for ABA and it is one of the most common events, especially in a raid encounter. We have to re-evaluate all rules then, so it naturally leads to some load on the CPU. I do want to revisit the rule updating mechanism when time permits, but I don't expect huge savings on that end.

We don't listen to any combat log events though. Maybe custom rules could do some combat log processing but to a limited extent.

**Comment by Adirelle** [comment]
I don't if this changed over time but in the past, all processing done by Ace3 libraries was accounted to the first addon in the list embedding them, and has they are alphabetically sorted on Windows, Adi* addons are often at the top of the list. Have you done some tests with a standalone version of Ace3 installed ?

**Comment by Rainrider** [comment]
You might also look at LibArtifactData-1.0, which is also embedded into ABA. Especially if you also have WeakAuras installed. I have seen some WA scripts that use it and are [beyond words in terms of efficiency](https://github.com/Rainrider/LibArtifactData-1.0/issues/18). It could also be blamed on ABA if you run it embedded.

**Comment by arcadepro** [comment]
I don't use Weakauras, no. In the raid environment the mods used were Dominos, Tullarange, Bigwigs and ABA.

**Comment by Rainrider** [comment]
Closing this. Feel free to reopen is the need arise.
