### ISSUE TITLE
Dropdown menu for each rule to choose between 'bad' and 'good' borders

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#273]
Is it possible to have a dropdown menu for each rule to choose between 'bad' and 'good' borders (red and green colors) to be shown instead of having a pre defined 'good' or 'bad' border for each rule which will always show its corresponding color? With that in mind make an option to change the color of the highlights (borders and flash if possible).

**Comment by Rainrider** [comment]
You can change the colors of the "good" and "bad" borders under the Theme section in the settings. Other than that no. "Good" and "bad" are also a type of duality and will be kept like that.
