### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by Meksid** [AdiAddons/AdiButtonAuras#285]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2..0.15

#### How did you install the addon (curse client/manually)?
curse client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
release

#### If you installed manually, where did you download the addon from?
-

#### Which type of installation did you choose (nolib/normal)?
-

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: DK
  - Your spec: Unholy
  - Name of the spell (and spell id if known): Cold Heart 248406 (from legendary chest), Scourge of Worlds 191747
  - Source of the spell (core ability/talent/artifact/pvp):

#### If you have an error report, copy it below: 
how to remove the timer and leave only the stacks????

P.S. Inline aura was perfect addon...=(

**Comment by Rainrider** [comment]
The pre-patch for BfA will probably hit the live servers in the next 2 weeks so I don't see any sense in updating the live version and I'm fairly behind on class data for BfA, so I'd rather spend the little time I have there.

You can build yourself custom rules though - see https://github.com/AdiAddons/AdiButtonAuras/tree/master/doc

If this is useless to you or Inline Aura was that perfect, feel free to fix it or use another addon.

**Comment by Meksid** [comment]
Ty you for answer!
