### ISSUE TITLE
When over 4 stacks of Bone Shield the time left disappears

### ISSUE THREAD

**Issue by Graybt** [AdiAddons/AdiButtonAuras#294]
#### Additional Info
After dropping below 5 stacks the time left comes back.

#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.17

#### How did you install the addon (curse client/manually)?
Both

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### If you installed manually, where did you download the addon from?
Github

#### Which type of installation did you choose (nolib/normal)?
Both

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Death
  - Your spec: Blood
  - Name of the spell (and spell id if known): Bone Shield id:196181
  - Source of the spell (core ability/talent/artifact/pvp): Core ability

#### If you have an error report, copy it below:
N/A

**Comment by Rainrider** [comment]
I can't reproduce this, Bone Shield is displayed correctly on Marrowrend. Please check your custom rules. Btw the spell id of Bone Shield is 195181.

**Comment by Graybt** [comment]
Are you taking it past 4 stacks? I just tried deleting the saved variables files and using a freshly installed copy of the mod, so every thing is default, with no other mods running and it still doesn't show the timer when it goes past 4 stacks of Bone Shield.
When the stacks are less than or equal to 4 the timer shows up just fine.
That 196181 is a typo.

**Comment by Graybt** [comment]
After some more testing I've found that it only happens when you have Ossuary specced. 
When you have Foul Bulwark or Tombstone everything works as intended.

**Comment by Rainrider** [comment]
When you've talented into Ossuary, ABA activates an additional rule to show the Ossuary buff on Morrowrend. The Ossuary buff does not have a duration and the Ossuary rule takes precedence over the rule for Bone Shield, thus only the green border is being shown. The stack count is applied by the stock ui, this is why it is still visible.

Your options are:
  - deactivate the rule for Ossuary
  - create a custom rule to better suit your needs

Sadly there is no other way to control rules precedence in ABA.

**Comment by Graybt** [comment]
Understood.
 I would suggest maybe having the default having the rule deactivated as personally I think the timer is more important for bone shield as you can see how many stacks you have at any given time.
But as you said the fix is easy once you know the issue.
