### ISSUE TITLE
Vampiric Touch Priest

### ISSUE THREAD

**Issue by Vae2009** [AdiAddons/AdiButtonAuras#295]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.17

#### How did you install the addon (curse client/manually)?
twitch client

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Priest
  - Your spec: Shadow
  - Name of the spell (and spell id if known): Vampiric Touch
  - Source of the spell (core ability/talent/artifact/pvp): Ability

It works when the spell itself is on the action bar but no longer works anymore when in a macro, though it used to work perfectly. I also have Mind Flay in a separate macro that still works with your addon just fine.

#showtooltip
/cast [stance:1] Vampiric Touch; [nostance] Shadowform

#showtooltip
/stopmacro [channeling]
/cast Mind Flay

These are my macros, Mind Flay works but Vampiric Touch does not.

**Comment by Rainrider** [comment]
I'll look into it this evening.

**Comment by Rainrider** [comment]
Ok, ABA fails to get the proper target for the macro. This was introduced by https://github.com/AdiAddons/AdiButtonAuras/commit/97058bc839ea686f3444dbcdbd4ef823a3fd0830

A workaround for the time being is to change the macro to:
#showtooltip
/cast [**\@target**,stance:1] Vampiric Touch; [nostance] Shadowform

I'll try to fix this but with my current schedule it will take some time. Sorry about that

**Comment by Vae2009** [comment]
alright I will give that a try ty

**Comment by Rainrider** [comment]
@Vae2009 86ab7362694c8b8f27bd585054e5cffd04b5fa1b should fix the problem. A release will be up on twitch/curse in a few minutes.
