### ISSUE TITLE
Button overlays do not scale to match ElvUI Actionbar size

### ISSUE THREAD

**Issue by BanditBanditBandit** [AdiAddons/AdiButtonAuras#298]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.19

#### How did you install the addon (twitch client/manually)?
Twitch Client

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:
  - Your spec:
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

#### If you have an error report, copy it below:
When resizing my actionbars with ElvUI (I like having very large actionbars, so I put it on max size) the overlays provided by this addon do not match and show up as smaller squares inside of the icon. Using the INLINE AURA addon would scale the button overlay to the proper size. Is there any way you could fix this issue, its been present since you switched over to this rewrite.

**Comment by Rainrider** [comment]
I'll try to take a look at it this Wednesday. Maybe the ElvUI guys changed something, I think ABA used to work with it.

I don't know about InlineAura though. AFAIK it was discontinued 5 years ago. I don't know why you guys are still mentioning it or how it is relevant to ABA.

**Comment by Rainrider** [comment]
@BanditBanditBandit are the overlays sizes properly after reload?

**Comment by BanditBanditBandit** [comment]
I'm going to check when I get home! Thanks for working on it

**Comment by BanditBanditBandit** [comment]
![nope](https://user-images.githubusercontent.com/13251996/43869007-3bf40a3e-9b25-11e8-9f14-edffc607889c.jpg)

**Comment by BanditBanditBandit** [comment]
I can get onto discord if you want to test out changes quickly, Im back from work so I'll be around for a few hours at least.

**Comment by Rainrider** [comment]
It will still need a reload after you change the button sizes. To avoid this the ElvUI guys should fire LibActionButton's `OnButtonChanged` event when resizing the buttons (`LAB.callbacks:Fire('OnButtonChanged')`). It is up to you to tell them :)

**Comment by BanditBanditBandit** [comment]
Ok I will send this thread to the ElvUI guys.

**Comment by Rainrider** [comment]
To understand what I mean: open ElvUI config, change the size of the buttons, close the config. You will see that without reloading the ui the size of ABA's overlays remains unchanged. This is not critical as you probably won't change the bar sizes that often, that's why I said it is up to you to bug them about it.

**Comment by BanditBanditBandit** [comment]
Thanks for fixing it, I'm finally able to use the new version! I have been editing the old add-on to keep it working up until I took a break 1 year ago. I think the stance of the author was that they wouldn't support ElvUI at the time. It's nice to see more work going into this great add-on.

**Comment by Rainrider** [comment]
Thanks for the kind words, I'm glad it is working for you :)
