### ISSUE TITLE
Rule Request: HideStacks { SpellId, ... }

### ISSUE THREAD

**Issue by adraffy** [AdiAddons/AdiButtonAuras#30]
Many effects like Clearcasting and Nature's Grasp show stacks, yet there is only ever 1 (so it's visual noise.)  The same applies to Faerie Fire, which applies 3 stacks, but never less, so the 3 kind of pointless.

Possibly a rule type could be added:

HideStacks { 
      135700, -- Clearcasting
      16689, -- Nature's Grasp
}

Additionally (I should probably make a separate ticket for this, but it's minor) Druid.lua, Feral Clearcasting spell ID should be "135700" not "16870".

Anyway, I miss InlineAura (mine was heavily modified) but I like this new addon.  I look forward to using it in WoD.  Thanks!

**Comment by Rainrider** [comment]
Ancient :)
