### ISSUE TITLE
August updates not working for me.

### ISSUE THREAD

**Issue by Shackles70** [AdiAddons/AdiButtonAuras#300]
2.0.18-4-g97f7c9b

Twitch

Alpha

Using the alpha above because the target de-buffs are not working for me with the August updates, buffs work fine.
Doesn't seem to have any errors.

**Comment by Dephi73** [comment]
2.0.19
Twitch

the target de-buffs are not working for me, buffs work fine.
Doesn't seem to have any errors.

Version 2.0.18 works fine for me

**Comment by Rainrider** [comment]
Please stick with 2.0.18 for the time being, I need some time to fix this. Sorry about that :(

**Comment by Shackles70** [comment]
Thanks
