### ISSUE TITLE
Request: Glow Druid's Soothe when there is something to dispel

### ISSUE THREAD

**Issue by nickdekruijk** [AdiAddons/AdiButtonAuras#305]
No idea if it's even possible but like interrupting it would be nice to have my Soothe button light up whenever there is an enrage effect I can dispel.

**Comment by Rainrider** [comment]
Yes this is possible and is my top priority when I'm back from my vacation. Dispels for enrage effects are already in LibPlayerSpells, however I need a way to tell if a buff is an enrage effect. I hoped Blizzard would add some API for this but it seems not to be the case.

**Comment by nickdekruijk** [comment]
That would be awesome! Enjoy your vacation!
Let me know if you want me to test anything.
