### ISSUE TITLE
Feature Request for ele shamy's

### ISSUE THREAD

**Issue by Pillgar** [AdiAddons/AdiButtonAuras#306]
Not sure how to request a feature, but here goes.  Is it possible to show my maelstrom value on the earth shock spell?  I had this working previously to the current xpack, but for the life of me, I can not remember how I got it to work.  if anyone has a user rule I could copy and paste, I'd greatly appreciate it.

**Comment by Rainrider** [comment]
```lua
ShowPower {
    8042,
    'Maelstrom',
}
```

**Comment by Pillgar** [comment]
ty
