### ISSUE TITLE
Balance Druid Spells Missing

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#307]
Balance Druid talent spell 'Fury of Elune' is missing.
Balance Druid PVP talent spells 'Cyclone' and 'Faerie Swarm' are also missing.

**Comment by Rainrider** [comment]
Fury of Elune does not have an associated aura, so no way to track this other than the combat log, which is beyond the scope of ABA.

Both Cyclone and Faerie Swarm work for me. Do you have macros for those?

In the future please use the issue template when opening an issue as it helps me to verify some details about your installation and it has the question about macros which spares me the time to ask you explicitly about it and you the time for waiting for another response.

**Comment by mspykerez** [comment]
To bad that Fury of Elune can't be tracker :(

I have macro for Faerie Swarm.

**Comment by mspykerez** [comment]
I thought that the addon already worked with all macros by default! Anyway here is my macro:

#showtooltip Faerie Swarm
/click [overridebar][vehicleui][possessbar,@vehicle,exists]OverrideActionBarButton4
/stopmacro [overridebar][vehicleui][possessbar,@vehicle,exists]
/startattack
/cast Faerie Swarm

**Comment by Rainrider** [comment]
> I thought that the addon already worked with all macros by default!

I'm asking questions because I need to reproduce your bug in order to be able to fix it. This being said, your macro works for me.

**Comment by mspykerez** [comment]
Ya it's working now! Maybe didn't work before because I was still lvl 110.

**Comment by Rainrider** [comment]
I tested it at level 110 :)
