### ISSUE TITLE
Numbers not showing on 'neutral' mobs

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#310]
Since BFA I notice that the addon is not working (not showing spell countdowns for debuffs on target) at all on mobs that are neutral (can't be attacked) and then become hostile (most common encounter on role playing scenarios where a mob is talking and then starts attacking you). 

Happens on my Balance druid spells moonfire and sunfire.

**Comment by nickdekruijk** [comment]
I have the same issue! Also balance druid with moon-/sunfire. Maybe worth noting I'm using elvui. Haven't tried without that yet.

**Comment by Rainrider** [comment]
This is probably again due to the way I try to guess the unit's reaction in order to resolve dynamic units like enemy and ally. I'll take a look

**Comment by mspykerez** [comment]
It happens on dungeons bosses too where they appear as neutral then become enemy. I notice however that during an encounter if the boss goes under the surface and becomes untarget when he appears again as a enemy everything works fine. So it appears that something wrong happens in the 'transition' between neutral to enemy target.

**Comment by Rainrider** [comment]
Yes, I need to update dynamic units when the unit's reaction changes. I think I have a solution, but have to test it. A way for now would be to untarget the mob and target it again (I think).

Do you know a mob where I can test this? I don't have a max level char yet and not needing a group would be nice.

**Comment by nickdekruijk** [comment]
2nd boss freehold (turtle/shark) for example. But that would require a group ofc.
There are also some quest mobs you need to talk too and then become hostile.
