### ISSUE TITLE
Barbed Shot(spell=217200)  dot`s countdown is wrong

### ISSUE THREAD

**Issue by wonderzerg** [AdiAddons/AdiButtonAuras#313]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.22

#### How did you install the addon (twitch client/manually)?
manually

#### If you installed manually, where did you download the addon from?
curseforge/wowace

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Hunter
  - Your spec: Beast Mastery
  - Name of the spell (and spell id if known): Barbed Shot, spellid=217200
  - Source of the spell (core ability/talent/pvp):core ability
  - Do you use a macro to cast the spell (post the macro if so):

**Comment by wonderzerg** [comment]
some time when casting the spell, a addtional countdown is shown up. and then the countdown goes wrong(seems this addtional cd is added to that)

**Comment by Rainrider** [comment]
![barbebedshot](https://user-images.githubusercontent.com/363876/46244288-f1b20f80-c3dc-11e8-994b-55d8bb1274b7.png)
Disable the spells you don't need.

Also concerning the changed issue title - you probably found this out but just in case - azerite traits are not included.

**Comment by wonderzerg** [comment]
issue title is my fault ctrl + v ...
only check when buff found on pets seems OK.
