### ISSUE TITLE
Warlock: "Show missing" issues with Absolute Corruption and Unstable Affliction

### ISSUE THREAD

**Issue by monochrony** [AdiAddons/AdiButtonAuras#314]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.22

#### How did you install the addon (twitch client/manually)?
Manually

#### If you installed manually, where did you download the addon from?
Curse

#### Additional Information: ####
  - Your class: Warlock
  - Your spec: Affliction
  - Spells and IDs: 
Corruption (Spell ID: 172)
Absolute Corruption (Talent ID: 196103) 
Unstable Affliction (Spell ID: 30108)

Enabling "Show missing: Show Flash" for "Corruption", when using the "Absolute Corruption" talent. The talent makes the aura permanent, which results in a permanent Flash suggestion on the spell button.

Spell and Aura ID do not change with the talent.

---

Another minor issue: I'm using a user rule to display a shard count on Unstable Affliction:

`Showpower {30108, "SoulShards", 3, "flash"},`

The shard count disappears when targeting an enemy unit and "Show missing: Show flash" is enabled. Disabling the Suggestion/Flash on 3 Soul Shards does not solve the problem. It's possible to circumvent this issue by using another user rule instead of the default rule in LPS-WARLOCK-8.0.0-1:

`DebuffAliases {30108, 233490},`

**Comment by monochrony** [comment]
I managed to solve my problem with Absolute Corruption:

```
return Configure {
    'CorruptionMissingSuggestion',
    L['Suggest when Corruption is about to run out.'],
    172,
    'enemy',
    'UNIT_AURA',
    function(_, model)
        local found, _, expiration = GetDebuff('target', 146739)
        if not found or ((expiration - GetTime()) <= 5) then
            model.flash = true
        end
    end,
	  {63106,196102} -- Siphon Life, Writhe in Agony
}
```
By excluding Absolute Corruption as provider, I've managed to get the rule working for the other two talents in that row. `((expiration - GetTime()) <= 5)` doesn't seem to be as reliable as I'd like it to be, though. But it works for now.

**Comment by Rainrider** [comment]
I see what's causing it. I'll try to find a solution these days.

**Comment by Rainrider** [comment]
Closing this as it is quite old.
