### ISSUE TITLE
Help with show stacks

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#316]
Hello there! Can you figure out what I'm doing wrong here ?

```
return Configure {
	'Custom Arcanic Pulsar',
	'Shows the stacks of @NAME',
	78674, -- Starsurge (show the rule on this spell)
	'player', -- the event unit (where to look for the buff)
	'UNIT_AURA', -- the event for refreshing the rule
	function(_, model) -- code to be executed when the event fires
		local found, count = GetPlayerBuff('player', 287790) -- Arcanic Pulsar
		if found then
			model.count = count
		end
	end,
	287784, -- Arcanic Pulsar azerite trait (the provider spell)
}
```

Basically I want my Starsurge icon on the action bar to show the current number of Arcanic Pulsar stacks that I have on my char preferable allowing it to change color when it reaches the max number!

**Comment by Rainrider** [comment]
You can't use the azerite trait as a provider spell yet (ABA has no support for those for the moment). Just remove the spell and it should work. The downside is that the rule will be always active, regardless of if the trait is known.

**Comment by Rainrider** [comment]
Use [ShowStacks](https://github.com/AdiAddons/AdiButtonAuras/blob/master/doc/RulesRef.md#ShowStacks)'s `handlerOrThreshold` argument.

Btw azerite support will be coming with https://github.com/AdiAddons/LibSpellbook-1.0/pull/7. No ETA, but it should be soon-ish.

**Comment by Rainrider** [comment]
Azerite support is in as of 2.1.0. You can now use azerite traits as provider spells.
