### ISSUE TITLE
Missing Feral Druid Talent Skill

### ISSUE THREAD

**Issue by hnm-zz** [AdiAddons/AdiButtonAuras#317]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.23

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### If you installed manually, where did you download the addon from?
N/A

#### Which type of installation did you choose (nolib/normal)?
N/A

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Druid
  - Your spec: Feral
  - Name of the spell (and spell id if known): Primal Wrath spell=285381
  - Source of the spell (core ability/talent/pvp): Talent
  - Do you use a macro to cast the spell (post the macro if so): No

#### If you have an error report, copy it below:

No error report.

Primal Wrath is a finisher that is not being properly tracked by ABA. There is no combo point display, and no timer for the associated debuff, Rip.

**Comment by Rainrider** [comment]
This is a new talent introduced in patch 8.1. I currently don't have the bandwidth to update the class data for all classes. Feel free to issue a PR or create a custom rule for yourself.
