### ISSUE TITLE
Demon Hunter Vengeance Sigil of Flame Debuff missing

### ISSUE THREAD

**Issue by jbaedke** [AdiAddons/AdiButtonAuras#319]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.1.1
#### How did you install the addon (twitch client/manually)?
Twitch client
#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release
#### If you installed manually, where did you download the addon from?
N/A
#### Which type of installation did you choose (nolib/normal)?
Normal
#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Demon Hunter
  - Your spec: Vengeance
  - Name of the spell (and spell id if known): Sigil of Flame (204596 / 204513 with talent / target dot 204598)
  - Source of the spell (core ability/talent/pvp): Core / talent modified
  - Do you use a macro to cast the spell (post the macro if so): No
#### If you have an error report, copy it below:
I'm not seeing an error but I was able to get it working with a user rule:
return Configure {
    "Sigil of Flame",
    "Show Debuff when Enemy is affected by Sigil of Flame",
    {
		204596, -- Sigil of Flame (Vengeance)
		204513, -- Sigil of Flame (with Concentrated Sigils talent)
    },
    "target",
    { "UNIT_AURA" },
	function(_, model)
		local found, _, expiration = GetDebuff('target', 204598)
		if found then
			model.expiration = expiration
			model.highlight = 'bad'
		end
	end
}

**Comment by Rainrider** [comment]
Thanks for the report. Will be fixed in the next release.
