### ISSUE TITLE
Add Arms Warrior spell Skullsplitter (260643)

### ISSUE THREAD

**Issue by wsuhoey** [AdiAddons/AdiButtonAuras#322]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.1.1

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Warrior
  - Your spec: Arms
  - Name of the spell (and spell id if known): Skullsplitter (260643)
  - Source of the spell (core ability/talent/pvp): Talent level 15 (3)
  - Do you use a macro to cast the spell (post the macro if so):

Please, if feasible, also add a rule with something like:
`Show the "bad" border when CurrentRage is greater than or equal to (MaxRage - 20)`

This is because Skullsplitter generates 20 rage.

**Comment by Rainrider** [comment]
The "bad" border's default meaning is the presence of a debuff, which is not the case with Skullsplitter. Normally I would use the "darken" highlight type for what you want to achieve. As this would suggest the ability is unusable below max rage - 20 but it has a damage component as well, I'd rather not impose this as a default rule. You can ofc add it as a custom rule for yourself.
