### ISSUE TITLE
Additional text position options

### ISSUE THREAD

**Issue by tordenflesk** [AdiAddons/AdiButtonAuras#325]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.1.2-2-g3e94398

#### How did you install the addon (twitch client/manually)?
Manually

#### If you installed manually, where did you download the addon from?
CurseForge

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:
  - Your spec:
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

#### If you have an error report, copy it below:

https://i.imgur.com/Cmv8xEQ.png

As you might be able to tell from this screenshot. Charges and Stacks are in the same spot. I would love to be able to move one of them to another corner of the button. X+Y :)

**Comment by Rainrider** [comment]
![aba text options](https://user-images.githubusercontent.com/363876/58345437-a6131100-7e58-11e9-8bc1-b4017c9f3c52.png)
