### ISSUE TITLE
Any consideration of porting to WoW Classic

### ISSUE THREAD

**Issue by theredsox** [AdiAddons/AdiButtonAuras#326]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
8.0.1 I believe is the closest version to what Classic uses. It's a modification off of the 8.0 API even though classic will release as 1.13. So it's not really that far behind retail. Many mod creators from what I've read have had very little issue updating a version starting with a 8.0.1 version of their mod. Though I guess with Classic having spells which have been removed from retail, it might not be a quick port for this specific addon. Just curious if there is any hope.

#### How did you install the addon (twitch client/manually)?
I run this addon in retail and love it. Played Classic stress test today and it feels so lacking not having this wonderful addon.

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
You'd release it under 1.13. I think Twitch is adding a Classic category though. Not sure if it is there yet. I've been locating Classic addons through willitclassic.com so far.

#### If you installed manually, where did you download the addon from?
n/a

#### Which type of installation did you choose (nolib/normal)?
n/a

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: n/a
  - Your spec:
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

#### If you have an error report, copy it below:
 n/a

Cheers,
~Brandon

**Comment by Rainrider** [comment]
TBQH I don't see myself doing it. Haven't looked at the classic API yet so can't tell how hard it will be to port ABA. Spell information is provided by LibPlayerSpells-1.0 and it will have to be updated/forked for Classic.

**Comment by vegidio** [comment]
I also would love to have this addon ported to WoW Classic, especially with the great success that has being since relaunch.

**Comment by Adirelle** [comment]
IIRC, the wow 1.0 API was terrible ; it's been 14 years since though, so my memory might fail me. Unless they just ported the classic content on the modern engine with the modern API, I do not think porting ABA is feasible. I am still looking for documentation about that API, BTW.

**Comment by eugals** [comment]
As far as I read [here](https://www.reddit.com/r/classicwow/comments/ai67k2/world_of_warcraft_classic_api_for_addon/?st=k03h9s69&sh=3c42d6a9) and [there](https://www.mmo-champion.com/threads/2450394-AddOns-API-and-Scripting-of-Classic-WoW) it's mostly a replica of the modern API with some modifications.
> I am still looking for documentation about that API, BTW.

[This topic](https://www.wowinterface.com/forums/showthread.php?p=332165) might help hopefully.

**Comment by vegidio** [comment]
@Adirelle I heard the same thing that @eugals mentioned. Apparently the WoW Classic API is essentially the same of the retail version, with some minor changes so I assume it wouldn't be so difficult to port it to WoW Classic :)

By the way, I love your addons. I use a couple of them! Thanks for putting your time on this.

**Comment by harl** [comment]
@Adirelle Thank you for looking into this, as well as that Classic-tagged AdiBags upload, showing that you're taking things into consideration.
Hopefully, you can make use of the Classic API to get ABA to work with it too.
ABA is definitely one of those qol addons that greatly help to "act professionally" in this game without taking away from the game's own charm.

**Comment by pmk24** [comment]
@Adirelle would love if this got ported to classic, if it does I don't mind sending some paypal to help the beer\pizza balance ^^

**Comment by Adirelle** [comment]
Sorry to disappoint you, guys. The problem is that I am not playing on classic and I haven't the motivation to port all the libraries used by ABA, let alone rebuilding the spell databases. If Rainrider doesn't feel it either, I think this isn't going to happen.
