### ISSUE TITLE
Show flash per rule based

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#329]
Is it possible to make the 'show flash instead' an option per default rule meaning it will be flashing if rule A is detected and showing the good border (red for example) if rule B is detected, instead of all rules would flash when 'show flash instead' is selected on that spell.

**Comment by Rainrider** [comment]
You have full control over the highlight type through custom rules. The `Spells & Items` are bound to the action (the spell or item placed in the action button), not to auras .

**Comment by mspykerez** [comment]
Ah ye I was just wondering if it would be possible to add an easy way to change each rule highlight method for the default rules since those rules are mostly good enough instead of using custom rules.
