### ISSUE TITLE
[Shaman] missing spells

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#330]
The following spells are missing for elemental shaman:

-Earth Shock (I wish to create a rule to show the number of stacks the Azerite Trait 'Lava Shock' currently has applied for Earth Shock)
-Icefury talent (want to use with show missing threshold)
-Stormkeeper talent (want to use with show missing threshold)
-Lightning Lasso pvp talent (want to use with show missing threshold)

-Concentrated Flame essence (show the number of stacks we currently have)

**Comment by Rainrider** [comment]
The shaman data hasn't been updated since the release of BoA. Feel free to contribute to [LibPlayerSpells-1.0](https://github.com/AdiAddons/LibPlayerSpells-1.0).

Azerite traits and essences are supported only through custom rules.
