### ISSUE TITLE
[WIP] Classic Support

### ISSUE THREAD

**Issue by pctD** [AdiAddons/AdiButtonAuras#333]
I'm fairly new to WoW addon dev but I put in some work the past couple days to get familiar with the environment and try to get AdiButtonAuras working in Classic.

I've opened the following WIP PRs to get AdiButtonAuras working and implemented for Hunter. See ![adiclassic](https://user-images.githubusercontent.com/56284637/66450565-df19df80-ea0d-11e9-8f99-8b847fe7c4d2.jpg)

The PRs:
https://github.com/AdiAddons/AdiButtonAuras/pull/332
https://github.com/AdiAddons/LibSpellbook-1.0/pull/8
https://github.com/AdiAddons/LibPlayerSpells-1.0/pull/136

I'd like to push this across the finish line, and I had some questions around future support and I was hoping to open the dialog.

Some questions below:
- Should the libraries live in a separate Classic repo, or just a separate branch? I think a separate repo makes the most sense but I'll leave that up to you.
- Should AdiButtonAuras live in a Classic repo, on a separate branch (with all non-classic stuff stripped), or should I wrap all of the classic/non-classic stuff in conditionals? I'm open to any of these options.

**Comment by Rainrider** [comment]
I think branches won't work with the current build system. We use tags to trigger a push and they don't live on a specific branch. Also LibPlayerSpells is released as a separate addon so if ppl pull it into their repos by using latest tag, they might get a classic release instead of live.

Users filing issues without tagging classic might be an annoyance as well. This is minimized when using separate repos.

**Comment by pmk24** [comment]
pctD many thanks for looking into this as it will improve many peoples experience in classic! if you need any testing on either mage or priest please let me know and once you have a good alpha drop me your paypal and I will help with the beer\pizza fund <3

**Comment by ntry** [comment]
I am also willing to help with a donation. I miss this feature very much and would be very happy if you continue here. Should you need a Warlock or Holypriest for testing, please let me know.
