### ISSUE TITLE
Rule to activate spell flash for less than 20% HP

### ISSUE THREAD

**Issue by FelipeOrtuzarSawred** [AdiAddons/AdiButtonAuras#338]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
**AdiButtonAuras-2.2.0**

#### How did you install the addon (twitch client/manually)?
**twitch client**

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
**Release**

#### If you installed manually, where did you download the addon from?
**N/A**

#### Which type of installation did you choose (nolib/normal)?
**N/A**

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: **Hunter**
  - Your spec: **Marksmanship**
  - Name of the spell (and spell id if known): **Sniper Shot**
  - Source of the spell (core ability/talent/pvp): **Talent PvP**
  - Do you use a macro to cast the spell (post the macro if so): **N/A**

#### If you have an error report, copy it below: **N/A**

**I just need to create a ruler to trigger flash of the spell when enemy is below 20% HP**

Please

**Comment by FelipeOrtuzarSawred** [comment]
Why nobody responds? What should I do to help me with what I need? Donate? Answer me, thanks @Adirelle @ckaotik @Rainrider

**Comment by Rainrider** [comment]
I don't have an active subscription so can't look up the spell ids for you but this was an old rule for warriors' Execute:
```lua
Configure {
	"Execute",
	format(L["%s when %s is below %s%% health."], DescribeHighlight("hint"), DescribeAllTokens("enemy"), 20),
	{ 5308, 163201 }, -- Execute
	"enemy",
	{ "UNIT_HEALTH", "UNIT_MAXHEALTH" },
	function(units, model)
		local foe = units.enemy
		local maxHealth = UnitHealthMax(foe)
		if maxHealth <= 0 then return end
		if UnitHealth(foe) / maxHealth <= 0.20 then
			model.hint = true
		end
	end,
}
```

And [here](https://github.com/AdiAddons/AdiButtonAuras/blob/master/doc/RulesRef.md#Configure) is the general description of the Configure rule.
