### ISSUE TITLE
Feature Request: Support for DiabolicUI

### ISSUE THREAD

**Issue by PersonalProxy** [AdiAddons/AdiButtonAuras#339]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.2.0

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

### Feature Request: Add support for DiabolicUI
Hello, I have been trying for a few weeks to incorporate support for AdiButtonAuras into a bar addon I use called [DiabolicUI](https://github.com/GoldpawsStuff/DiabolicUI).
I have confirmed from the addon author the naming scheme for the buttons is:
`EngineBarXButtonY`
...so I edited the core.lua (_of AdiButtonAuras_) as follows:

 	if IsAddOnLoaded('Dominos') then
		self:ScanButtons("DominosActionButton", 120)
	end

	if IsAddOnLoaded('Bartender4') then
		self:ScanButtons("BT4Button", 120)
		self:ScanButtons("BT4PetButton", NUM_PET_ACTION_SLOTS)
		self:ScanButtons("BT4StanceButton", NUM_STANCE_SLOTS)
	end

	if IsAddOnLoaded('DiabolicUI') then
		self:ScanButtons("EngineBar1Button1", 1)
		self:ScanButtons("EngineBar1Button2", 1)
		self:ScanButtons("EngineBar1Button3", 1)
		self:ScanButtons("EngineBar1Button4", 1)
		self:ScanButtons("EngineBar1Button5", 1)
		self:ScanButtons("EngineBar1Button6", 1)
		self:ScanButtons("EngineBar1Button7", 1)
		self:ScanButtons("EngineBar1Button8", 1)
		self:ScanButtons("EngineBar1Button9", 1)
		self:ScanButtons("EngineBar1Button10", 1)
		self:ScanButtons("EngineBar1Button11", 1)
		self:ScanButtons("EngineBar1Button12", 1)
		self:ScanButtons("EngineBar2Button1", 1)
		self:ScanButtons("EngineBar2Button2", 1)
		self:ScanButtons("EngineBar2Button3", 1)
		self:ScanButtons("EngineBar2Button4", 1)
		self:ScanButtons("EngineBar2Button5", 1)
		self:ScanButtons("EngineBar2Button6", 1)
		self:ScanButtons("EngineBar2Button7", 1)
		self:ScanButtons("EngineBar2Button8", 1)
		self:ScanButtons("EngineBar2Button9", 1)
		self:ScanButtons("EngineBar2Button10", 1)
		self:ScanButtons("EngineBar2Button11", 1)
		self:ScanButtons("EngineBar2Button12", 1)
		self:ScanButtons("EngineBar3Button1", 1)
		self:ScanButtons("EngineBar3Button2", 1)
		self:ScanButtons("EngineBar3Button3", 1)
		self:ScanButtons("EngineBar3Button4", 1)
		self:ScanButtons("EngineBar3Button5", 1)
		self:ScanButtons("EngineBar3Button6", 1)
		self:ScanButtons("EngineBar3Button7", 1)
		self:ScanButtons("EngineBar3Button8", 1)
		self:ScanButtons("EngineBar3Button9", 1)
		self:ScanButtons("EngineBar3Button10", 1)
		self:ScanButtons("EngineBar3Button11", 1)
		self:ScanButtons("EngineBar3Button12", 1)
	end

Now, I am **not** a programmer, so I am simply gleaning from how you supported Bartender4 and Dominos that this is the correct way to add support for DiabolicUI since we have confirmed the naming scheme of the buttons.

However, this approach doesn't work, all of my attempts thus far have failed to allow AdiButtonAuras to function with DiabolicUI.
If you could provide any insight to what I may be doing wrong, that would be great.

Here is the response I got from Goldpaw (_author of DiabolicUI_):

> @PersonalProxy the naming scheme for standard actionbar buttons in the current live version of Diabolic is EngineBarXButtonY, where X is the bar number, Y is the button number. 

> However, if you are trying to attach things to it by its name, before that the buttons have tons of subframes above its framelevel. So simply attaching a texture to that frame probably won't work, it needs to be in a frame some 3-4-5 framelevels above the diabolic button or something similar, and update the framelevel when the diabolic button does.

**Thanks for your time, have a pleasant day.**

**Comment by Rainrider** [comment]
I'm sorry I don't think I am going to do that.
