### ISSUE TITLE
Shadowland update

### ISSUE THREAD

**Issue by Echalote** [AdiAddons/AdiButtonAuras#340]
Hello,

Any chance to have an update for Shadowland? This addon is so essential.

Cordially,

Echalote

**Comment by Rainrider** [comment]
I do have beta access and have done some very minor fixes for Shadowlands already. However I can't make any promises. Two things I will definitely not do - item buffs and class data. I will create a sticky issue for Shadowlands support the coming days.

**Comment by Echalote** [comment]
Thanks for the update, i'am glad. This addon is so usefull, i can't play whitout it ! U guys did an amazing work !

I truly hope u'll succeed ! : )
