### ISSUE TITLE
How to not order the addon to not open BugGrabber

### ISSUE THREAD

**Issue by Hitsuwalker** [AdiAddons/AdiButtonAuras#344]
Hello !

Message: Couldn't open Interface\AddOns\AdiButtonAuras\libs\BugGrabber\load.xml
Time: Tue Sep  1 05:04:35 2020
Count: 3

I removed BugGrabber from Folders cuz Give to me a lot of bug.

I just wanna resolve this error thanks

**Comment by Nulgar** [comment]
Personally, I delete this line from the .toc file after updating AdiButtonAuras and AdiBags:
`libs\BugGrabber\load.xml`

I find that even the outdated tekErr is more useful than BugGrabber.
