### ISSUE TITLE
Shadowlands beta : Error on button overlay in options menu

### ISSUE THREAD

**Issue by VaporAPX** [AdiAddons/AdiButtonAuras#345]
Hi there, when opening the options menu and clicking on "Spells and Items" for the button overlay, the following error fires.

![Aba](https://user-images.githubusercontent.com/21989751/92232625-b55a7a00-ee63-11ea-87ee-f2bf2a344454.jpg)

**Comment by VaporAPX** [comment]
Also, several abilities aren't lighting up appropriately even though their spell ID's haven't changed from live to beat.  An example of this is Keg Smash for Brewmaster monk.  Live and Beta IDs are the same, but on the beta the border doesn't light up.  Spear Hand strike is another, same ID's, doesn't flash on an interruptable spell.

**Comment by Rainrider** [comment]
The first one is fixed on the shadowlands branch. I am aware of the second one.

**Comment by Rainrider** [comment]
The second issue is fixed on the shadowlands branch of LibSpellbook-1.0
