### ISSUE TITLE
Auras dont show up on extra action bars (2,7,8,9,10).

### ISSUE THREAD

**Issue by siven80** [AdiAddons/AdiButtonAuras#349]
When using bar numbers 2,7,8,9,10 on Dominos action bars, the button auras dont show up. But they do on the normal bars 1,3,4,5,6.

#### Which version of AdiButtonAuras are you using (enter the exact version number here)? 
9.0.0

#### How did you install the addon (twitch client/manually)?
twitch client

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
release

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:
  - Your spec:
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

**Comment by Rainrider** [comment]
I will take a look at this but don't have an ETA for you.

**Comment by siven80** [comment]
Ah no bother, turns out it is a dominos issue as it works fine with bartender.
