### ISSUE TITLE
9.0 Configuration UI non functional due to broken Ace3 libs.

### ISSUE THREAD

**Issue by arcadepro** [AdiAddons/AdiButtonAuras#350]
Probably a known issue but just making it an actual bug.

Installing https://www.wowace.com/projects/ace3/files/3078383 will fix it for now if anyone discovers this bug during the pre-patch addon apocalypse.

**Comment by mario-64** [comment]
AdiButtonAuras is tainting my other Ace3 addons.  is this why?

**Comment by Rainrider** [comment]
Ah, nope, I have just released before Ace3 pushed their Shadowlands compatible tag I assume.

@arcadepro just install Ace3 as a separate addon and it should fix it. The next release will have the right Ace3 version embedded.

@mario-64 this sounds like a separate issue.

**Comment by arcadepro** [comment]
Yeah, I know. I posted the fix to stop people inevitably making bugs about it.

**Comment by Rainrider** [comment]
Pushed a new release, so it should be fine now.
