### ISSUE TITLE
Support dynamically created action buttons using the ActionBarActionButtonMixin template

### ISSUE THREAD

**Issue by Tuller** [AdiAddons/AdiButtonAuras#351]
This is a followup on #349 The issue with Dominos is that I create action buttons later in the cycle (after PLAYER_LOGIN) so your ScanButtons call isn't catching those.

```lua
hooksecurefunc(ActionBarActionButtonMixin, "OnLoad", function(button)
   -- initialize button here
end)
```

This doesn't cover anything that's created before AdiButtonAuras sets up the hook, but it does cover everything afterwards.

**Comment by arcadepro** [comment]
Oh, this is possibly why some rules were failing on the Beta when I was swapping specs at the test dummies to fix spell data changes.

**Comment by Rainrider** [comment]
https://github.com/AdiAddons/AdiButtonAuras/commit/29dc5fb91e2af92494f6ffab93a87aad4967a4ce should address this issue.

@Tuller is this enough of a fix or do I miss something here?

On a side note, mouse hovering over Dominos buttons seems to trigger the Update function twice (on stock ui it is once). Not sure if you are double dipping somewhere, please discard this if it is non-sense.

**Comment by Tuller** [comment]
That looks like it would work for just Dominos. I was going for an approach that would hopefully cover everything

**Comment by Rainrider** [comment]
Sadly I can't hook the mixin or the ActionBarButtonTemplate. I already tried the former in 893132f7f36ecebbbe2014f33ab0cad3f46f8204.

I would close this then, please feel free to reopen if you have any follow-ups.

**Comment by Rainrider** [comment]
Ah I can actually use the ActionBarActionButtonMixin, it just does not work for the stock ui action buttons for whatever reason.
```lua
hooksecurefunc(ActionBarActionButtonMixin, 'Update', function(button)
	addon:Debug('Mixin hook fired', button:GetName())
end)
```
just never fires for the stock ui.

**Comment by Rainrider** [comment]
`hooksecurefunc` replaces the original function by a wrapper, this is why hooking the mixin does not work for the stock ui - I can't hook it before the stock consumes the mixin.

Still leaning basics after all those years :) Thanks again @Tuller for making me realize my gaps :)

**Comment by Tuller** [comment]
Hurray :)
