### ISSUE TITLE
Failed CI feedback and Github release

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/AdiButtonAuras#352]
@Adirelle for some reason we don't get feedback from TravisCI anymore and Github releases fail.

The last commit with feedback is af15d1a87b02b88641fd50bd158104115dca6164.
The last proper build is https://travis-ci.org/github/AdiAddons/AdiButtonAuras/builds/537557370.

The builds fail with:
```
Creating GitHub release: https://github.com/AdiAddons/AdiButtonAuras/releases/tag/9.0.0
Error! (401)
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
Would you mind checking [on a solution](https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025) as I don't have much of access here. I'm also fine with moving to Github Actions, if you want to make the switch.

**Comment by Adirelle** [comment]
I have done the steps on your link. Tell me if it fixes something, or not.

Swithing to Github Actions sounds interesting, too. However, I do not have much time to do it myself now, so feel free to try it yourself.

**Comment by Rainrider** [comment]
Seems to work now, thanks!

I can switch to Actions but you will have to [add the secrets to github](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets). Would be good if you keep the names `CF_API_KEY` and
`GITHUB_OAUTH` like in [here](https://github.com/BigWigsMods/packager#uploading).

**Comment by Rainrider** [comment]
@Adirelle done :)

Build with errors: https://github.com/AdiAddons/AdiButtonAuras/actions/runs/309550734 (check the annotations both in the build overview and in the Lint step of the build job)

I also added conditional building - only tags will be pushed to CurseForge, all builds will be pushed Github (not sure if this works as you haven't added the secrets yet).

Tell me if you think.

**Comment by Adirelle** [comment]
Nice, though github does not create a link from the report to the source file.

I will try to take a look at the secrets this weekend.

**Comment by Adirelle** [comment]
> Would be good if you keep the names `CF_API_KEY` and
> `GITHUB_OAUTH` like in [here](https://github.com/BigWigsMods/packager#uploading).

Done for CF_API_KEY.
I cannot add a secret named GITHUB_OAUTH because ["secret names must not start with the GITHUB_ prefix."](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#about-encrypted-secrets) but a token is automatically provided for Actions.

**Comment by Adirelle** [comment]
According to its code, BigWigsMods/packager only upload tagged verions, so I suggest using the [actions/upload-artifact](https://github.com/actions/upload-artifact) action.

**Comment by Adirelle** [comment]
cf. #355

**Comment by Adirelle** [comment]
I have merged the PR, updated the badge and removed travis-ci webhook, so we continue with github actions.
