### ISSUE TITLE
Rogue feedback

### ISSUE THREAD

**Issue by Echalote** [AdiAddons/AdiButtonAuras#356]
Hello,

Thx so much for the update ! I can't code myself nd i have to admit i'am pretty bad with this matter. I send some feedback on rogue assassination.

#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
9a17f26
#### How did you install the addon (twitch client/manually)?
Twich

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Alpha
#### Which type of installation did you choose (nolib/normal)?
No idea :(

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Rogue
  - Your spec: Assasination
  - Name of the spell (and spell id if known): Slice and Dice (spell=5171)
  - Source of the spell (core ability/talent/pvp): Core ability
  - Do you use a macro to cast the spell (post the macro if so): No

#### If you have an error report, copy it below:
It's not an error but since Slice and dice is up again, the bufftime on button will be great.

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Rogue
  - Your spec: Assasination
  - Name of the spell (and spell id if known): Kick (spell=5171)
  - Source of the spell (core ability/talent/pvp): Core ability
  - Do you use a macro to cast the spell (post the macro if so): No

#### If you have an error report, copy it below:
No longer glow when we have to kick.

Thx u for help,

Faufilé

**Comment by Rainrider** [comment]
Apart from the rogue data not being up-to-date for Shadowlands it is strange that LPS does not pick up Kick (spell id: 1766) as an interrupt.

`/run local lps = LibStub('LibPlayerSpells-1.0'); print(bit.band(lps:GetSpellInfo(1766), lps.constants.INTERRUPT) > 0);`

I'll take a look later, this is rather strange.

**Comment by Echalote** [comment]
Run local lps on wow? (sorry for being noob : /)

**Comment by Rainrider** [comment]
> No longer glow when we have to kick.

This has been broken for two years ...

**Comment by Rainrider** [comment]
I won't be updating the rogue data anytime soon. Unless someone contributes to it, it will sadly stay as it is (the kick will be fixed with the next release though)
