### ISSUE TITLE
DOTS/HOTS on custom bars

### ISSUE THREAD

**Issue by MattABS** [AdiAddons/AdiButtonAuras#357]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?

9a17f26

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Alpha

#### Which type of installation did you choose (nolib/normal)?
N/A

Kind of a strange error. On my Druid, if using a HOT like Regrowth or a DOT like Sunfire, it doesn't provide the length left of the spell on the spell itself if it's on a bar from another addon. However, if I drag the spell onto the default blizzard bars, both types work as expected.

This wasn't a problem before the prepatch. I'm not receiving any LUA errors when casting or hovering over the icons.

**Comment by Rainrider** [comment]
I'll ask my crystal ball what this mysterious "other addon" is.

**Comment by MattABS** [comment]
It was [G15 Buttons](https://www.curseforge.com/wow/addons/g15-buttons-continued), but also tried it with [Neuron](https://www.curseforge.com/wow/addons/neuron) too. Though it may be something with those addons, as bars in [Bartender4](https://www.curseforge.com/wow/addons/bartender4) seem to work OK.

**Comment by Rainrider** [comment]
G15 Buttons was last updated in 2014. Neuron seems updated for Shadowlands, but we can't support every action bar addon out there.

Supported are: Bartender4, Dominos, nMainbar (from NeavUI), ElvUI and every other LibActionButton-1.0 based addon out there willing to call `AdiButtonAuras:RegisterLab` (like the action bars in LS: UI i.e.). Please either use one of those or ask the actionbar addon authors to add support for ABA.
