### ISSUE TITLE
Unstable Affliction of Affliction Warlock can‘t showing dot time

### ISSUE THREAD

**Issue by ParanoidBarnett** [AdiAddons/AdiButtonAuras#358]
i love it,thx coder
i use curseforge 9.0.1 (2020-10-14) ver. 
Unstable Affliction of Affliction Warlock can‘t showing dot time,
pls fix it,thx

**Comment by arcadepro** [comment]
Fixed in next version. https://github.com/AdiAddons/LibPlayerSpells-1.0/blob/9754b29ad3ee2d6c920c2d3aa79127e07e9d8cc5/data/Warlock.lua

**Comment by Rainrider** [comment]
Closed with AdiAddons/LibPlayerSpells-1.0@a84d6c636671a862a6906a3f842439dc7aa0c67b
