### ISSUE TITLE
updating rogue

### ISSUE THREAD

**Issue by aristes** [AdiAddons/AdiButtonAuras#364]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
9.0

#### How did you install the addon (twitch client/manually)?
manually

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
/

#### If you installed manually, where did you download the addon from?
courseforge

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Rogue
  - Your spec: Assasination
  - Name of the spell (and spell id if known): Slice and Dice
  - Source of the spell (core ability/talent/pvp): core ability
  - Do you use a macro to cast the spell (post the macro if so): no

#### If you have an error report, copy it below:

Slice and Dice spell doesn't highlight if is on. I know someone reported it and it was fix but I don't know how to update files, what do I have to download and where to put it?.

**Comment by Rainrider** [comment]
Please be kind to use the already existing issue for your problem next time. This would have been #361 in this case.

An alpha release should be up on CurseForge shortly, install it manually or toggle alpha releases in the Twich client.
