### ISSUE TITLE
'No flash on cooldown' threshold

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#367]
Implement a slider with a value that we can set for when the option 'No flash on cooldown' is enable so an ability can always flash not when the cooldown reaches 0 but like lets say 5s before it reaches 0.

**Comment by Rainrider** [comment]
We have this already. https://github.com/AdiAddons/AdiButtonAuras/issues/269

**Comment by mspykerez** [comment]
What we have doesn't work when you have the option 'No flash on cooldown' enabled.
