### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by Krazy74** [AdiAddons/AdiButtonAuras#372]
#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Druid
  - Your spec: Balance
  - Name of the spell (and spell id if known): Sunfire/Moonfire
  - Source of the spell (core ability/talent/pvp): DoT
  - Do you use a macro to cast the spell (post the macro if so): No

#### If you have an error report, copy it below:

There is no error. I did not know where else to ask a question. I want to know if there is a rule to either fade out the button when it is not applied on my target? I can add a flash which is also ok however is there a way to have it only flash when in combat? This is for when the DoT is not applied I have the flash on however it stays on even out of combat and would like it to only flash when in combat and not applied. Or if we can have the button just appear faded when not applied?

**Comment by BanditTech** [comment]
there is a global setting to only display in combat
