### ISSUE TITLE
Spirit Bomb

### ISSUE THREAD

**Issue by voidedzim** [AdiAddons/AdiButtonAuras#374]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
9.0.2

#### How did you install the addon (twitch client/manually)?
Twitch

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release I think

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: DH
  - Your spec: Veng
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

#### If you have an error report, copy it below:

No error but have a question if thats ok- I am trying to build a custom rule to glow a button at 5 stacks for a Vengeance DH's Spirit Bomb when Frailty is about to expire on a target but am not sure how to have a user rule meet 2 required conditions. Is that possible? Here is what I have right now: (the first half works, it lights up when I reach 5 stacks, but it also lights up while Frailty is still on my target.) 

`
return {
ShowStacks {
    247454, -- Spirit Bomb
    203981, -- Soul Fragments
    5,
    "player",
    5,
    "flash"
},

PassiveModifier {
    247454, -- Spirit Bomb
    247454, -- Spirit Bomb
    247456, -- Fraility
    "enemy",
    "flash"
}

}
`

Is there anyway to force both these rules at the same time before performing a glow?

**Comment by Rainrider** [comment]
You have to use a `Configure` rule if you want to check multiple conditions in one rule.

```lua
return Configure {
	'SpiritBombNoFrailty',
	'Put you description here',
	247454, -- Spirit Bomb
	{'player', 'enemy'},
	'UNIT_AURA',
	function(units, model)
		local hasFragments, numFragments = GetPlayerBuff('player', 203981) -- Soul Fragments
		if not hasFragments or numFragments < 5 then return end

		local hasFrailty, _, expiration = GetPlayerDebuff(units.enemy, 247456) -- Frailty
		local timeLeft = hasFrailty and (expiration - GetTime()) or 0;

		if timeLeft < 5 then
			model.flash = true
		end
	end,
}
```

The above will work for anywhere between 5 secs left of Frailty on your enemy and the debuff not being present. This is because ABA relies on the events to refresh the display of custom rules. You might want to rather use the "Show missing threshold" option, however you can't define the number of soul fragments for it.
