### ISSUE TITLE
my rule and my type of HIGHLIGHT

### ISSUE THREAD

**Issue by aristes** [AdiAddons/AdiButtonAuras#375]
How can i modify this code to HIGHLIGHT as "FLASH" not "GREEN". I know there is global option but I have two buffs shown on the same spell stacking...

return SelfBuffAliases {315496, 121153}

**Comment by Rainrider** [comment]
I assume you want to show a flash on Slcie and Dice when Blindside is on the player. If so, something like that should work:

```lua
return Configure {
	'BlindslideSlice',
	BuildDesc('HELPFUL PLAYER', 'flash', 'player', 121153),
	315496, -- Slice and Dice
	'player',
	'UNIT_AURA',
	function(_, model)
		local hasBlindside = GetPlayerBuff('player', 121153)
		if hasBlindside then
			model.flash = true
		end
	end,
	121153, -- Blindside
}
```

**Comment by aristes** [comment]
Hey! Thanx a lot. 
I have another problem on my shaman with Winfury Totem and Legendary Doom Winds.
How can I make Windfury Totem red - 8512 when Doom Winds Sated debuff is on - 335904?
