### ISSUE TITLE
Support for Button_Forge

### ISSUE THREAD

**Issue by Nosnevs** [AdiAddons/AdiButtonAuras#380]
#### Describe what you'd like to see implemented
Hi. 

would it be possible to implement support for the Button_Forge addon?

**Comment by Rainrider** [comment]
I could try to offer some sort of API through which action bars authors could add support for ABA themselves like it is for those using LibActionButton currently but I probably won't have the time for that in the near future. If the authors of Button_Forge would like to contribute, I would gladly accept a pull request.
