### ISSUE TITLE
Game stuttering while healing dungeons as Resto Shaman

### ISSUE THREAD

**Issue by PaCozz** [AdiAddons/AdiButtonAuras#381]
Game starts stuttering when healing dungeons on a Restoration Shaman. 

#### Version (*):
9.0.3

#### Bug description (*):
Game starts stuttering when healing dungeons on a Restoration Shaman. 

I noticed this during regular gameplay at first, and then tested a Mythic+ Theater of Pain and Mythic+ Mists of Tirna Scithe. In both runs i was experiencing fps stutters. I was not able to reproduce the issue while standing in Oribos without a group.

During the mists run I used an addon called "Addon Usage"  to track CPU usage. Screenshot of the data is included below. The odd thing is that i play multiple classes, and the shaman is the only one ive noticed a performance issue with. I could be totally wrong about the cause, but im submitting this ticket since the Addon Usage pointed to AdiButtonAuras being a possible suspect.

#### Class and spell data:
Healing Tide Totem (108280) or Cloudburst totem (157153) could be the cause.

I use a macro for Healing Tide which activates Orc Racial and a Use trinket.

#showtooltip Healing Tide Totem
/cast Blood Fury
/use 13
/cast Healing Tide Totem

#### What did you expect?
Performance should not suffer noticably in regular group content.

#### How to reproduce:
1. Join a group for a Shadowlands Dungeon
2. Keep using Cloudburst and Healing Tide Totem constantly throughout the run
3. Observe minor stutters while in combat

#### Screenshots:
![mists_fps_stutter](https://user-images.githubusercontent.com/78828265/107440787-de7ee500-6b3c-11eb-9a81-937e6ad0764b.png)

**Comment by Rainrider** [comment]
Thank you for the nice report!

TBH I don't see how the two totems would be the cause of it. You could make a run with those deactivated and see if it changes something. You could try deactivating the rule for Bloodlust/Heroism as it tracks group auras and its handlers fire a lot more often than personal rules, maybe this would make a difference.

**Comment by PaCozz** [comment]
I did some further testing, disabled all addons and turned them on/off one by one and im 80% sure AdiButtonAuras is the reason for the micro stutters. To do a dungeon specific test I had to keep Dominos action bars enabled since I am lazy and didnt want to rebind my buttons entirely.

Regarding the stutters:
Cloudburst Totem seems to be the issue here, and since the spell is split into 2 different spells (Cloudburst Totem & Recall Cloudburst Totem) the rules are also only active for the Recall spell.  An additional bug I noticed while testing was that the rules (green border / timer) occasionally fails to show for recall cloudburst for whatever reason. Could this failure to show be the cause of the stutter? I'm assuming some check fails in the background which causes an issue in the code which then causes the stutters.

My conclusion:
A bug with Recall Cloudburst Totem rules or some kind of conflict between Dominos + AdiButtonAuras + Cloudburst Totem.

**Comment by arcadepro** [comment]
This cloudburst stuttering is in the base client but ABA seems to make it visibly worse. It's been like this for years.

**Comment by mbattersby** [comment]
Is this related to #388 ?

**Comment by Rainrider** [comment]
@PaCozz could you test if this got better with the latest version (9.1.0)?

**Comment by PaCozz** [comment]
> 
> 
> @PaCozz could you test if this got better with the latest version (9.1.0)?

Issue appears to be fixed in 9.1.0. I completed a Mythic+ Spires of Ascension with the 9.1.0 version and did not notice any stuttering during regular gameplay. This was only 1 run so far, but I'll report back in case i notice any further issue.  Thanks!
