### ISSUE TITLE
Shadow Word : Pain isnt working properly (several lua errors at the begining of ui load)

### ISSUE THREAD

**Issue by velainur** [AdiAddons/AdiButtonAuras#386]
#### Version (*):
9.0.3(202-12-30)

#### Bug description (*):
Shadow Word: Pain is not working properly (spannish version)

#### Class and spell data:
Holy/Shadow Priest (no matter which subclass is used, it still get bugged)

#### Error messages i got from the begining...
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.
[13:52:53] [Error 000001DFD0439900] captured, click the link for more information.

#### First LUA related Error (Not sure if it related with the debuff i suspect)
Interface\AddOns\AdiButtonAuras\core\Overlays.lua:327: Attempt to register unknown event "UNIT_DEBUFF"
[13:53:02] [string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\AdiButtonAuras\core\Overlays.lua"]:327: in function <Interface\AddOns\AdiButtonAuras\core\Overlays.lua:269>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AdiButtonAuras\core\Overlays.lua"]:255: in function <Interface\AddOns\AdiButtonAuras\core\Overlays.lua:253>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\AdiButtonAuras\core\Core.lua"]:407: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0-27\general-General.lua"]:656: in function `handler'
[string "@Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0-27\core.lua"]:27: in function `?'
[string "@Interface\AddOns\AdiButtonAuras\libs\LibSpellbook-1.0-27\core.lua"]:44: in function <...AddOns\AdiButtonAuras\libs\LibSpellbook-1.0\core.lua:43>

**Comment by Rainrider** [comment]
This is not an error from AdiButtonAuras but rather caused from a custom rule. You are trying to register an event (UNIT_DEBUFF) that does not exist.
