### ISSUE TITLE
[Rogue] Invalid spell identifier: 199804

### ISSUE THREAD

**Issue by Faycop** [AdiAddons/AdiButtonAuras#396]
BugSack is spamming me this error:

`1048x ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: Invalid spell identifier: 199804
[string "=[C]"]: ?
[string "@AdiButtonAuras\core\RuleDSL.lua"]:98: in function <AdiButtonAuras\core\RuleDSL.lua:93>
[string "@AdiButtonAuras\core\RuleDSL.lua"]:126: in function <AdiButtonAuras\core\RuleDSL.lua:125>
[string "@AdiButtonAuras\core\RuleDSL.lua"]:197: in function <AdiButtonAuras\core\RuleDSL.lua:196>
[string "=[C]"]: ?
[string "@AdiButtonAuras\core\Core.lua"]:405: in function `?'
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@AdiButtonAuras\libs\LibSpellbook-1.0-28\general-Generale.lua"]:656: in function `handler'
[string "@AdiButtonAuras\libs\LibSpellbook-1.0-28\core.lua"]:27: in function `?'
[string "@AdiButtonAuras\libs\LibSpellbook-1.0-28\core.lua"]:44: in function <AdiButtonAuras\libs\LibSpellbook-1.0\core.lua:43>`

I'm not fond on Lua, but looking on google it seems that spell identifier 199804 is "Between the eyes": [https://www.wow-freakz.com/spells.php?spell=199804](https://www.wow-freakz.com/spells.php?spell=199804)

But if I look for the same spell on wowhead it gives me another spell identifier (235484): [https://www.wowhead.com/spell=235484/between-the-eyes](https://www.wowhead.com/spell=235484/between-the-eyes)

Is it possible to fix this or is caused by something else on my UI?

I'm currently playing subtlety so the spell "Between the eyes" is not available for me.

Thanks in advance for the support and the effort put so far to give us this little gem of an addon :)

**Comment by Rainrider** [comment]
199804 is the pre-Shadowlands spell id for Between the Eyes. This has been fixed in LPS https://github.com/AdiAddons/LibPlayerSpells-1.0/commit/65411725547ae1dbcf78c8f1e25969d49d7e1d8d#diff-a68a41cda4fc1c3033719e3f7aecab5f15cba3b3f28a419a70cd21c89e15b05eL53, so I suppose you have a custom rule with the given ID. Removing the rule or updating it should resolve the problem.

**Comment by Faycop** [comment]
> 199804 is the pre-Shadowlands spell id for Between the Eyes. This has been fixed in LPS [AdiAddons/LibPlayerSpells-1.0@6541172#diff-a68a41cda4fc1c3033719e3f7aecab5f15cba3b3f28a419a70cd21c89e15b05eL53](https://github.com/AdiAddons/LibPlayerSpells-1.0/commit/65411725547ae1dbcf78c8f1e25969d49d7e1d8d#diff-a68a41cda4fc1c3033719e3f7aecab5f15cba3b3f28a419a70cd21c89e15b05eL53), so I suppose you have a custom rule with the given ID. Removing the rule or updating it should resolve the problem.
Hi @Rainrider, thanks for your quick reply! :)

![WoWScrnShot_042222_113207](https://user-images.githubusercontent.com/1913375/164679034-693cac5d-3376-4ad5-886c-489769a0d8c5.jpg)

Actually I don't have any custom rule, and I've already tried to reinstall the addon and to delete the .lua and .lua.bak of AdiButtonAuras in the WTF folder, sadly with no luck :(

**Comment by Rainrider** [comment]
Ah damn, no new version of ABA was released since the rogue data has been updated. You also have the message in chat, that the spell data for ROGUE is for the previous expansion. I'll push an update later today or tomorrow. You could also install LibPlayerSpells-1.0 as a normal addon, which should fix the issue for you as well.

**Comment by Rainrider** [comment]
I pushed a version for 9.2 which should fix your issue. There is still old class data (rogue is up-to-date though), but I lack the time and inclination to update all classes myself.
