### ISSUE TITLE
Game Crash with Shaman 4 pc Tier set 

### ISSUE THREAD

**Issue by Bharts8** [AdiAddons/AdiButtonAuras#397]
#### Bug description (*):
When using 4 Pc Theurgic Starspeakers Regalia, after using either Fire elemental or Storm Elemental, moments later the game freezes and the only way out is to alt f4. I believe the issue to be that the callback in the Shaman Rules  [BuildTempPetHandler](https://github.com/AdiAddons/AdiButtonAuras/blob/e0d5b95fe1b9e587ecd3dbefe6fa69d11f572591/rules/Shaman.lua#L37) is not properly handling the pet time remaining due to the new interaction and can potentially get into an infinite loop. Was able to confirm that the crashing stops if I insert a limiter in the loop to only allow 'remaining' to ever go to 10 minutes, however that's a bit of a hack so probably not worth a PR in favor of something more elegant

#### Class and spell data:
- class and spec: Elemental Shaman
- spell name and id: Fireheart  https://ptr.wowhead.com/spell=364472/fireheart
- spell source (core ability/talent/pvp/...): Storm Elemental or Fire Elemental

#### How to reproduce:
4Pc Theurgic Starspeakers Regalia is required in order to reproduce. Once you obtain 4 pc, Upon first using Fire elemental or Storm elemental, moments later the game will freeze and the only way to exit is by alt-f4.

**Comment by Rainrider** [comment]
I don't play a shaman, so correct me if I'm wrong, but given the current mechanics it is not possible to extend the duration of the elemental indefinitely (1.5 secs duration increase per cast, with 2 charges on 8 sec recharge).

Maybe `GetPetTimeRemaining()` is returning something funny in those situations, idk. Maybe you could test this like outputting the value of `GetPetTimeRemaining() / 1000`.

Either way restricting the timer to 10 min is fine with me, so feel free to submit your fix if it fixes it for you.

**Comment by CleverChrononaut** [comment]
My wife has had this issue as well and she really misses adibuttonauras as there's no other addon that does a similar thing. I've done a bit of coding, but I'm not familiar with LUA syntax. How would you go about setting a limit on the BuildTempPetHandler function?

**Comment by Bharts8** [comment]
@CleverChrononaut See Above PR.

**Comment by CleverChrononaut** [comment]
I appreciate it. I'll try it out.
