### ISSUE TITLE
Buffs without duration don't work with "Show Missing"

### ISSUE THREAD

**Issue by Nulgar** [AdiAddons/AdiButtonAuras#400]
#### Version (*):
9.2.1

#### Bug description (*):
Choosing anything other than "none" for "Show Missing" on buffs without a duration causes the "Show Missing" logic to not work.
Affected buffs are e.g. Druid Forms, or those from certain Items/Toys such the Highmountain [War Harnesses](https://www.wowhead.com/items/name:War+Harness?filter=129;0;99574) or the Honor Level [Pennants](https://www.wowhead.com/items/name:Pennant?filter=216;1;0) & the [Jolly Roger](https://www.wowhead.com/item=150547/jolly-roger)
_(I noticed this for the items and only while writing this realized this could also affect regular spells)_

#### What I was able to find out a.k.a. I hope this is not backseat programming:
With the model having an expiration time of 0, the function `overlayPrototype:UpdateState` in core/Overlays.lua can never recognize the buff as present, therefore always showing the "Show Missing" highlight.

I was able to achieve the expected behavior by changing the line
`if timeLeft < missingThreshold then`
to
`if timeLeft < missingThreshold and not model.highlight then`
but I suspect this is a very dirty fix, based on my limited understanding of the code.

_edit:_ started writing this issue yesterday and must have somehow missed the issue templates, edited to at least resemble the Bug report template. Please add Bug label, I don't seem to be able to do this post-creation.

**Comment by Nulgar** [comment]
I appreciate the effort of this elegant ingame workaround, should've thought of that myself, but I instead immediately went to hacking my copy :D

**Comment by Rainrider** [comment]
The reason I am reluctant to use your solution is that it might have side effects I do not see. The reasons I see custom rules as a sufficient solution in this case:

- item auras are outdated as the wowhead parser has been broken for years now (so auto-generated rules for items from recent expansions are likely broken or non-existent)
- other use-cases you provided (like druid auras) require custom rules anyways as there are no auto-generated rules for them currently
- if you feel comfortable with editing the core code, the custom rules syntax should be no problem for you.

So I'd close this for now.
