### ISSUE TITLE
WotLK Classic?

### ISSUE THREAD

**Issue by SebyS7** [AdiAddons/AdiButtonAuras#402]
Hi! i have read that you will not build your addon for classic. But this was for BC Classic.

Any Chance that maybe you have change your mind, since the Lichking is back? :)

**Comment by pmk24** [comment]
+1 for some WOTLK classic support, would donate a bunch if it helps as I miss the addon greatly!

**Comment by Schwartvogel** [comment]
Yep, would donate too!

**Comment by SebyS7** [comment]
me too

**Comment by drocks** [comment]
I would also love it! I have absolutely hated to build weak auras for every class and ability. I love love love this add on for retail and would love to have it for both.

**Comment by Rainrider** [comment]
No, sry, see https://github.com/AdiAddons/AdiButtonAuras/issues/326
