### ISSUE TITLE
fixed version for dragonflight

### ISSUE THREAD

**Issue by Nosnevs** [AdiAddons/AdiButtonAuras#408]
I've tried to remove all errors and add the Evoker. Not all spells have been added yet.. I hope it works. The other classes are not updated yet.

[https://www.curseforge.com/wow/addons/adibuttonauras-fx](https://www.curseforge.com/wow/addons/adibuttonauras-fx)

**Comment by Kyrgune** [comment]
Are you planning to update it for all classes?  Thankyou in either case!

**Comment by Nosnevs** [comment]
> Are you planning to update it for all classes? Thankyou in either case!

Most of the classes work, I haven't noticed any major bugs yet. If anyone finds a spell that needs to be added, please post here.

**Comment by Ukhai** [comment]
Will be trying this out this week on mostly Warlock/Priest/Warrior. Will report back, thanks!

**Comment by Pillgar** [comment]
Oh Nice!!!!  Gonna try it out right now.

**Comment by Rainrider** [comment]
Please take a look at https://github.com/AdiAddons/AdiButtonAuras/pull/409/files

The options can be loaded with only with the chat command `/aba` for now until I figure out how to fix them properly. I hope I can release this the coming days. I won't be doing class data updates, so feel free to contribute your classes.

**Comment by Rainrider** [comment]
Version 10.0.0 has been released and should be up on Curse shortly.

Thank you @Nosnevs for the efforts!

If anybody wants to be updating class data, please open a PR to either LibPlayerSpell-1.0 or here. Alternatively just use your custom rules in-game.
