### ISSUE TITLE
Is this intended (dark grey default button colors)?

### ISSUE THREAD

**Issue by 40P3** [AdiAddons/AdiButtonAuras#410]
Hi,

See picture. By default the buttons are very dark. Is this intended?

Also, if not, then might be related to other addons of mine that builds upon the default bar:
-tularange
-OmniCC
-MacroToolkint (longer macros so modified macro buttons on all my buttons)
-Masque

Regards,
H0PE

**Comment by 40P3** [comment]
Got it. It's your Maque Backdrop support is missing or broken. If I turn backdrop on for AdiButtonAuras, icons go invisible, backdrop shows only even though active icons/macros should be visible.
If I turn down the backdrop to be opaque then icons show properly.
![World Of Warcraft Screenshot 2023 02 21 - 00 27 31 95](https://user-images.githubusercontent.com/20872247/220212575-ee311407-b1a0-4187-84ed-0da3d64021ef.png)
![World Of Warcraft Screenshot 2023 02 21 - 00 27 29 20](https://user-images.githubusercontent.com/20872247/220212582-317d3a2f-7da8-43fa-9b4c-343521eec03b.png)

**Comment by Rainrider** [comment]
You do not want a backdrop on ABAs overlays because they are placed over your action buttons. This is working as intended. If you want to add a backdrop and don't see what is beneath the overlay, then this is your preference. There is definitely no backdrop turned on by default, but I'll take a look to make sure.

**Comment by 40P3** [comment]
Are you able to reproduce this on your end? I can reproduce it with any masque skin on any characters/classes/races.

**Comment by Rainrider** [comment]
Those are my Masque settings:
![image](https://user-images.githubusercontent.com/363876/220447934-e4d064b2-e158-46bc-89dd-01964535832e.png)

I cannot remember ever changing those but I have been using it like that like for 14 years(?) and yes backdrop is disabled there.

This is the code adding Masque support:
https://github.com/AdiAddons/AdiButtonAuras/blob/master/core/Display.lua#L196-L235

It works for me like that. If I enable the backdrop in the Masque settings, a backdrop appears and the underlying button is hidden. This is what I would expect to be quite honest. The user MUST have the ability to override defaults. If you set a tick in that checkbox, you want a backdrop, so you get a backdrop.

So, please tell me what do you expect me to do, when it is fixed for you when you uncheck that checkbox? Was the backdrop selected by default and you want it to not be selected by default?

**Comment by 40P3** [comment]
Hi,
Ok I've changed my settings seems working now, I've turned off backdrop on adibuttonauras and its good now. Thanks!
