### ISSUE TITLE
Nothing is visible on the buttons?

### ISSUE THREAD

**Issue by 40P3** [AdiAddons/AdiButtonAuras#411]
#### Version (*):
Latest version 10.0.0

#### Bug description (*):
On Rogue, nothing on the buttons.

#### Class and spell data:
Using Macros, some of them are longer than 255 char but some are just simple 3-4 spells on them with macro conditions, etc.
However when I turn the bar to another page with simple buttons or food or professions on them they aren't showing either.

#### How to reproduce:
Reload didnt helk,
Turnng off Adibuttonauras the only solution at the moment
no UI errors

![World Of Warcraft Screenshot 2023 02 18 - 07 03 00 39](https://user-images.githubusercontent.com/20872247/219844206-08f716c4-4112-4317-83c1-3a37da7d0978.png)

**Comment by Rainrider** [comment]
What action bar addon are you using? Can you reproduce this if you disable it?

**Comment by 40P3** [comment]
> What action bar addon are you using? Can you reproduce this if you disable it?

Cpmpletely default action bar, just changed the buttons around. :) Only addons I have that might change the buttons are macros, with some of them longer than 255 characters (just a few), with Macro Toolkit, Tularange, Masque and OmniCC.

**Comment by Rainrider** [comment]
It works for me.

![aba](https://user-images.githubusercontent.com/363876/219864785-edddab78-c745-4104-b96b-98d32b965e8b.gif)

Please try to reproduce this with ABA as the only addon. If it works, start other addons one by one until you figure out the offender, then post here.

**Comment by 40P3** [comment]
It's Masque. On my rogue the skin theme selected is CleanUI Edged

**Comment by Rainrider** [comment]
This must be either your skin or your Masque version. Tried all the stock skins and they work. Also tried Dominos and Caith, worked as well. Update your addons.

**Comment by 40P3** [comment]
Hi,

Sorry for the slow response. Masque with default vanilla bars and Masque Blizzard Bars addon.
Updating via curse app, so I got the latest versions.
https://www.curseforge.com/wow/addons/masque 10.0.6
https://www.curseforge.com/wow/addons/masque-blizz-bars-revived 10.0.5.1
I'll try to reinstall adibuttonauras and see what's going on.
