### ISSUE TITLE
Can't get Warrior Rend Ability to show

### ISSUE THREAD

**Issue by Pillgar** [AdiAddons/AdiButtonAuras#414]
Rend doesn't seem to display by default, so I used: 

return DebuffAliases {
     772, -- Rend
     772, -- Rend
}

Still with no luck.  Any idea's what I'm doing wrong?

**Comment by Rainrider** [comment]
You are probably using the wrong IDs. This is what I see on my prot warrior

Debuff ID: 388539
Spell ID: 394062 (Prot) and 772 (Arms)

The rule you need is:

```lua
return DebuffAliases {
	{
		   772, -- Arms Rend
		394062, -- Prot Rend
	},
	388539, -- Debuff Rend
}
````

This is what debugging tooltip gives you btw

![rend](https://user-images.githubusercontent.com/363876/236648211-b9032f46-3a1b-4672-a6dc-31916ecefe6e.jpg)
![rend_arms](https://user-images.githubusercontent.com/363876/236648479-d6dd8907-8f49-4c29-8447-ddc0a8b1b058.jpg)

**Comment by Pillgar** [comment]
TYVM Kind sir.
