### ISSUE TITLE
Errors on login and while playing about Invalid Spell Identifier

### ISSUE THREAD

**Issue by Neascari** [AdiAddons/AdiButtonAuras#415]
#### Version (*):
<10.0.1>

#### Bug description (*):
Whenever i log in, and while playing i get a lot of Error Messages regarding Adibuttonauras in the Chat.
The errors happen even if i only load this addon and no other.

#### Class and spell data:
Not related to any specific spells because the errors occures whithout me doing anything, but maybe it's still important.
I'm playing a shadow Priest.

#### Error report:
Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua:197: Invalid spell identifier: 193223
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua"]:98: in function <Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua:93>
[string "@Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua"]:126: in function <Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua:125>
[string "@Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua"]:197: in function <Interface/AddOns/AdiButtonAuras/core/RuleDSL.lua:196>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiButtonAuras/core/Core.lua"]:403: in function `?'
[string "@Interface/AddOns/AdiButtonAuras/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ras/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiButtonAuras/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ras/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdiButtonAuras/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/AdiButtonAuras/libs/LibSpellbook-1.0-29/general.lua"]:638: in function `handler'
[string "@Interface/AddOns/AdiButtonAuras/libs/LibSpellbook-1.0-29/core.lua"]:27: in function `?'
[string "@Interface/AddOns/AdiButtonAuras/libs/LibSpellbook-1.0-29/core.lua"]:44: in function <...AddOns/AdiButtonAuras/libs/LibSpellbook-1.0/core.lua:43
```

**Comment by xapollyon** [comment]
just for reference this is a shadow priest error

located in priest.lua

193223 Surrender to Madness (Shadow) -  no longer used in dragonflight
186263, -- Shadow Mend (Discipline) - no longer used in dragonflight

**Comment by suttoko** [comment]
263406, -- Surrendered to Madness (Shadow) - no longer used in dragonflight
too
