### ISSUE TITLE
NDui Compatibility/Support

### ISSUE THREAD

**Issue by DrkWntr** [AdiAddons/AdiButtonAuras#416]
Unless I am remembering wrong, before the most recent update I use to be able to run NDui and AdiButtonAuras at the same time. Sadly this is no longer the case. While having only these two addons enabled no overlays appear on any spells. Is there plans to add support or compatibility again at some point in the future? 

Note: I dug through NDui files and notice they use 'LibActionButton-1.0' - knowing nothing about LUA I did read another ticket that said it is supposed to be compatible? [link](https://github.com/AdiAddons/AdiButtonAuras/issues/380#issuecomment-771984356) 

Any help is much appreciated or if this is something I would have to contact NDui's author for would also be great to know. Thanks!

**Comment by Rainrider** [comment]
@DrkWntr the author of NDui could support ABA. See https://github.com/AdiAddons/AdiButtonAuras/pull/315.
