### ISSUE TITLE
lua error in 10.1

### ISSUE THREAD

**Issue by Pillgar** [AdiAddons/AdiButtonAuras#417]
When I mouse over an ability, I get Lua error's referencing AdiButtonAuras in the latest wow update:

Message: ...nterface/AddOns/AdiButtonAuras/core/DebugTooltip.lua:147: attempt to index field 'info' (a nil value)
Time: Tue May  2 23:01:15 2023
Count: 1
Stack: ...nterface/AddOns/AdiButtonAuras/core/DebugTooltip.lua:147: attempt to index field 'info' (a nil value)
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:544: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539>
[string "=[C]"]: in function `SetAction'
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:2243: in function `SetTooltip'
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:1950: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1943>
[string "@Interface/AddOns/Bartender4/libs/LibActionButton-1.0/LibActionButton-1.0.lua"]:1028: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1026>

Locals: self = GameTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:1112
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 GetProcessingTooltipInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:488
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:429
 AppendInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:525
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 AppendInfoWithSpacer = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:531
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:505
 IsTooltipType = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:509
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 ClearHandlerInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetUnitAura = <function> defined =[C]

**Comment by Dudditz** [comment]
DebugTooltip.lua is creating all the errors. We do not need it to play the game and use the addon. 

Simply open AdiButtonAuras\core\core.xml and delete the last line 
<Script file="DebugTooltip.lua"/>

save the file and you should be error free.

**Comment by Pillgar** [comment]
That worked.  TYVM!!

Can you help me with another problem I'm having?  I can't seem to get Thrash - 106830 (feral druid), or Rend - 772 (Warrior), to display the "bad" border when said debuff's are applied.  Both these abilities are dots, and they appear inside the "Spells & Items" menu, and are checked, but no display for these dots on their icons.  Not sure what's going on.  Any help would be greatly appreciated.
