### ISSUE TITLE
new buff causing issues with lua

### ISSUE THREAD

**Issue by xapollyon** [AdiAddons/AdiButtonAuras#420]
there is a new buff causing the following errors: - the buff us : New Niffen No-Sniffin' Tonic (amongst others)

Is there a way of incorporating aninput where we can add new buffs, items buffs , etc so the addon will see new buffs and not crash?

6x AdiButtonAuras/core/Items.lua:86: attempt to call upvalue 'BuildDesc' (a nil value)
[string "@AdiButtonAuras/core/Items.lua"]:86: in function <AdiButtonAuras/core/Items.lua:67>
[string "@AdiButtonAuras/core/Items.lua"]:104: in function <AdiButtonAuras/core/Items.lua:102>
[string "@AdiButtonAuras/core/Utils.lua"]:48: in function <AdiButtonAuras/core/Utils.lua:46>
[string "@AdiButtonAuras/core/Items.lua"]:122: in function <AdiButtonAuras/core/Items.lua:120>
[string "@AdiButtonAuras/core/Core.lua"]:423: in function `GetActionConfiguration'
[string "@AdiButtonAuras/core/Overlays.lua"]:270: in function <AdiButtonAuras/core/Overlays.lua:269>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:1742: in function `method'
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:1179: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1176>
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:1272: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1250>

Locals:
itemId = 86573
buffName = "Flesh to Stone"
name = "Shard of Archstone"
_ = "|cff0070dd|Hitem:86573::::::::70:253:::::::::|h[Shard of Archstone]|h|r"
_ = 3
_ = 1
_ = 1
_ = "Miscellaneous"
_ = "Other"
_ = 1
_ = ""
_ = 135241
_ = 0
itemClassId = 15
token = "ally"
filter = "HELPFUL PLAYER"
highlight = "good"
rule = <table> {
 events = <table> {
 }
 keys = <table> {
 }
 handlers = <table> {
 }
 name = "Shard of Archstone"
 units = <table> {
 }
}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
buffId = 127249
key = "item:86573:ally:HELPFUL PLAYER:good:127249"
(*temporary) = nil
(*temporary) = "HELPFUL PLAYER"
(*temporary) = "good"
(*temporary) = "ally"
(*temporary) = 127249
(*temporary) = "attempt to call upvalue 'BuildDesc' (a nil value)"
GetItemInfo = <function> defined =[C]:-1
GetItemTargetFilterAndHighlight = <function> defined @AdiButtonAuras/core/Items.lua:47
select = <function> defined =[C]:-1
BuildKey = <function> defined @AdiButtonAuras/core/Utils.lua:86
BuildDesc = nil
format = <function> defined =[C]:-1
LIBVer = 9
LibItemBuffs = <table> {
 enchantments = <table> {
 }
 __itemBuffs = <table> {
 }
 GetDatabaseVersion = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:143
 slots = <table> {
 }
 GetInventorySlotList = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:101
 IsItemBuff = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:41
 GetBuffItemID = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:84
 GetBuffInventorySlot = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:49
 __UpgradeDatabase = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:148
 __databaseVersion = 201809090817229
 trinkets = <table> {
 }
 GetItemBuffs = <function> defined @AdiButtonAuras/libs/LibItemBuffs-1.0/LibItemBuffs-1.0.lua:109
 consumables = <table> {
 }
}
descriptions = <table> {
}
tinsert = <function> defined =[C]:-1
BuildBuffIdHandler = <function> defined @AdiButtonAuras/core/Items.lua:55

**Comment by Rainrider** [comment]
1. New Niffen No-Sniffin' Tonic is not causing any problems (verified in game).
2. Flesh of Stone is displayed on Shard of Archstone (verified in game).
3. I cannot reproduce the error you posted, please delete your local copy of ABA and reinstall from curseforge.
4. Issue templates do make bug reports more readable. Please try to use that the next time you post an issue.
