### ISSUE TITLE
Feral, Trash

### ISSUE THREAD

**Issue by Lockomotion** [AdiAddons/AdiButtonAuras#421]
Hi.
I have the problem that the duration of Trash is not shown on the button. Can you help me?

Greetings, Lockomotion

**Comment by Lockomotion** [comment]
Thx a lot. It works. Great work !!!!  :-)

**Comment by Lockomotion** [comment]
Thx a lot for it. Do you have a new solution? After last update it did not work again. 

Greetings. lockelive

Gesendet von Mail für Windows

Von: Sliva
Gesendet: Dienstag, 10. Oktober 2023 14:30
An: AdiAddons/AdiButtonAuras
Cc: Lockomotion; Author
Betreff: Re: [AdiAddons/AdiButtonAuras] Feral, Trash (Issue #421)

add to _retail_\Interface\AddOns\AdiButtonAuras\libs\LibPlayerSpells-1.0\data\Druid.lua
at line 44
after
192090, -- Thrash (bear)
add that
405233, -- Thrash (cat)
and
at line 246
after
[192090] = 77758, -- Thrash (bear)
add
[405233] = 106830, -- Thrash (cat)

**Comment by Rainrider** [comment]
Sorry, I have missed this one. The update overwrote your local changes. I will make a PR later today addressing this

**Comment by Rainrider** [comment]
While I have added the new Thrash id to LibPlayerSpells, it would have been better to fix it client side by using a [user rule](https://github.com/AdiAddons/AdiButtonAuras/blob/master/doc/RulesRef.md#user-rules) (see [DebuffAliases](https://github.com/AdiAddons/AdiButtonAuras/blob/master/doc/RulesRef.md#DebuffAliases):

```
return DebuffAliases {
    106830, -- Thrash (cat - action)
    405233, -- Thrash (debuff)
}
```

I simply lack the time to update class data, so using user rules as long nothing is broken, is the preferred way to do it.

**Comment by Lockomotion** [comment]
Thx alot, i have copied this, put it in the user rule, and…….

IT WORKS !   😊))))

Thx a  lot !

Gesendet von Mail für Windows

Von: Rainrider
Gesendet: Mittwoch, 1. November 2023 11:45
An: AdiAddons/AdiButtonAuras
Cc: Lockomotion; State change
Betreff: Re: [AdiAddons/AdiButtonAuras] Feral, Trash (Issue #421)

While I have added the new Thrash id to LibPlayerSpells, it would have been better to fix it client side by using a user rule (see DebuffAliases:
return DebuffAliases {
    106830, -- Thrash (cat - action)
    405233, -- Thrash (debuff)
}
I simply lack the time to update class data, so using user rules as long nothing is broken, is the preferred way to do it.

**Comment by SlivaNilow** [comment]
in general, this is a very cool addon. I would like similar functionality out of the box. But...
Unfortunately, the addon is not updated very often and very much on duty.
As an alternative, I remade for myself on WeakAuras
The first version for the cat is here https://wago.io/AE0rJr0QO
By analogy, if desired, you can do it for the rest of the specks / classes.
I don't want anything, I'm not calling anyone anywhere. It will be great if the addon lives.
all the best, sorry for the English. I wrote through a translator

**Comment by Rainrider** [comment]
Issues here are either for problems with or for contributions to AdiButtonAuras. Advertising your own stuff here is just a dispaly of bad manners and disrespect to the work and time of others.
