### ISSUE TITLE
10.2.5 - After last Tuesday's patch anyone able to get it to work with Dominos?

### ISSUE THREAD

**Issue by Ukhai** [AdiAddons/AdiButtonAuras#424]
So far not showing any of my warlock or mage's auras on the bar. Trying to see if I can play around with it. 

 - This is currently with Dominos.

Upon further research Dominos re-wrote their stuff that other authors need to code in their own support. So... I guess I'll just have to not use Dominos for now.

**Comment by Mortiana** [comment]
Can confirm that it is not working on dominos for priest warlock evoker and paladin. I think it's safe to say it does not work on Dominos at all. We need a propper update please

**Comment by Ukhai** [comment]
> Can confirm that it is not working on dominos for priest warlock evoker and paladin. I think it's safe to say it does not work on Dominos at all. We need a propper update please

Think it'd be easier to switch to another action bar addon until Dominos finishes their stuff.  The default UI is doing okay for now but I might try out Bartender.
