### ISSUE TITLE
TWW Prepatch Errors

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiButtonAuras#426]
8x ...Ons/AdiButtonAuras/libs/LibSpellbook-1.0-29/general.lua:577: attempt to call global 'GetSpellBookItemInfo' (a nil value)
[string "@AdiButtonAuras/libs/LibSpellbook-1.0-29/general.lua"]:577: in function <...Ons/AdiButtonAuras/libs/LibSpellbook-1.0/general.lua:572>
[string "@AdiButtonAuras/libs/LibSpellbook-1.0-29/general.lua"]:611: in function `handler'
[string "@AdiButtonAuras/libs/LibSpellbook-1.0-29/core.lua"]:27: in function `?'
[string "@AdiButtonAuras/libs/LibSpellbook-1.0-29/core.lua"]:44: in function <AdiButtonAuras/libs/LibSpellbook-1.0/core.lua:43>

Locals:
bookType = "spell"
numSpells = 32
offset = 0
changed = false
(for index) = 1
(for limit) = 32
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "spell"
(*temporary) = "attempt to call global 'GetSpellBookItemInfo' (a nil value)"
============================================================================
83x AdiButtonAuras/core/Overlays.lua:290: attempt to call upvalue 'GetSpellLink' (a nil value)
[string "@AdiButtonAuras/core/Overlays.lua"]:290: in function <AdiButtonAuras/core/Overlays.lua:272>
[string "=(tail call)"]: ?
[string "@AdiButtonAuras/core/Overlays.lua"]:258: in function `ForceUpdate'
[string "@AdiButtonAuras/core/Overlays.lua"]:252: in function <AdiButtonAuras/core/Overlays.lua:251>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@AdiButtonAuras/core/Core.lua"]:349: in function `Initialize'
[string "@AdiButtonAuras/core/Core.lua"]:267: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

Locals:
self = MultiBarLeftButton10Overlay {
 Highlight = MultiBarLeftButton10OverlayHighlight {
 }
 __MSQ_bType = "Legacy"
 __MSQ_oType = "Frame"
 button = MultiBarLeftButton10 {
 }
 __Regions = <table> {
 }
 spellId = "item:188152"
 parentCount = MultiBarLeftButton10Count {
 }
 conf = <table> {
 }
 actionType = "item"
 actionId = 188152
 __MSQ_Addon = "AdiButtonAuras"
 Overlay = MultiBarLeftButton10OverlayOverlay {
 }
 events = <table> {
 }
 Count = MultiBarLeftButton10OverlayCount {
 }
 units = <table> {
 }
 Timer = MultiBarLeftButton10OverlayTimer {
 }
 unitMap = <table> {
 }
 guids = <table> {
 }
 unitConditionals = <table> {
 }
}
event = "AdiButtonAuras_Config_Changed"
actionType = "item"
actionId = 188152
macroConditionals = nil
conf = <table> {
 name = "Gateway Control Shard"
 keys = <table> {
 }
 handlers = <table> {
 }
 events = <table> {
 }
 units = <table> {
 }
}
enabled = true
spellId = "item:188152"
hasDynamicUnits = false
units = <table> {
}
events = <table> {
}
(*temporary) = MultiBarLeftButton10Overlay {
 Highlight = MultiBarLeftButton10OverlayHighlight {
 }
 __MSQ_bType = "Legacy"
 __MSQ_oType = "Frame"
 button = MultiBarLeftButton10 {
 }
 __Regions = <table> {
 }
 spellId = "item:188152"
 parentCount = MultiBarLeftButton10Count {
 }
 conf = <table> {
 }
 actionType = "item"
 actionId = 188152
 __MSQ_Addon = "AdiButtonAuras"
 Overlay = MultiBarLeftButton10OverlayOverlay {
 }
 events = <table> {
 }
 Count = MultiBarLeftButton10OverlayCount {
 }
 units = <table> {
 }
 Timer = MultiBarLeftButton10OverlayTimer {
 }
 unitMap = <table> {
 }
 guids = <table> {
 }
 unitConditionals = <table> {
 }
}
(*temporary) = "SetAction"
(*temporary) = "AdiButtonAuras_Config_Changed"
(*temporary) = nil
(*temporary) = "item:188152"
(*temporary) = "attempt to call upvalue 'GetSpellLink' (a nil value)"
addon = <table> {
 rules = <table> {
 }
 api = <table> {
 }
 AuraTools = <table> {
 }
 THEME_CHANGED = "AdiButtonAuras_Theme_Changed"
 groupUnits = <table> {
 }
 HIGHLIGHT_MEDIATYPE = "button_highlight"
 __LibSpellbook-1.0 = <table> {
 }
 RULES_UPDATED = "AdiButtonAuras_Rules_Updated"
 MOUSEOVER_CHANGED = "AdiButtonAuras_Mouseover_Changed"
 MOUSEOVER_TICK = "AdiButtonAuras_Mouseover_Tick"
 db = <table> {
 }
 overlayPrototype = <table> {
 }
 descriptions = <table> {
 }
 CONFIG_CHANGED = "AdiButtonAuras_Config_Changed"
 L = <table> {
 }
 libraries = <table> {
 }
 unitList = <table> {
 }
 dynamicUnitConditionals = <table> {
 }
 DYNAMIC_UNIT_CONDITONALS_CHANGED = "AdiButtonAuras_DynamicUnitConditionals_Changed"
 DEFAULT_SETTINGS = <table> {
 }
 GROUP_CHANGED = "AdiButtonAuras_Group_Changed"
}
GetSpellLink = nil
unitEvents = <table> {
 focus = "PLAYER_FOCUS_CHANGED"
 target = "PLAYER_TARGET_CHANGED"
 group = "AdiButtonAuras_Group_Changed"
 pet = "UNIT_PET"
 mouseover = "AdiButtonAuras_Mouseover_Changed"
}

**Comment by Rainrider** [comment]
I just pushed a release for The War Within (should be up shortly) which hopefully resolves the issues.
