### ISSUE TITLE
Warlock Shard tracking missing in 11.0

### ISSUE THREAD

**Issue by vderaa** [AdiAddons/AdiButtonAuras#427]
#### Version (*):
11.0.0

#### Bug description (*):
Warlock Shard Tracking missing from TWW update

#### Class and spell data:
Warlock - Certain spells requiring Soul Shards to cast used to track the shard count on the spell buttons and then flash when shards were capped. This appears to be missing in the TWW release.

An example of a spell that would use this is "Hand of Gul'dan - 105174"

#### What did you expect?
Shard Count should be present on any spells requiring the use of shards.  Usually seen on to Bottom Middle of the button

#### Screenshots:
![image](https://github.com/user-attachments/assets/ae9c7766-339c-4855-8696-2c458035f4a3)

Not sure if this is still a WIP after the class spell files were reworked to call the libs directly.  Regardless I added the below back into warlock.lua and it's working again.

ShowPower {
      {
          5740, -- Rain of Fire (Destruction)
          27243, -- Seed of Corruption (Affliction)
          -- 30108, -- Unstable Affliction (Affliction)
          104316, -- Call Dreadstalkers (Demonology)
          105174, -- Hand of Gul'dan (Demonology)
          116858, -- Chaos Bolt (Destruction)
          212459, -- Call Fel Lord (Demonology honor talent)
          267211, -- Bilescourge Bombers (Demonology talent)
          267217, -- Nether Portal (Demonology talent)
      },
          'SoulShards',
      }

**Comment by Rainrider** [comment]
Fixed in c52a76a063bee652c45360f426172ad63193ca65
